In [1]:
import pandas as pd
from datetime import datetime
import duckdb

1. Задача: «Лидеры категорий»
Контекст:
Маркетингу нужно выделить лояльных пользователей, которые тратят в конкретной категории значительно больше, чем «средний» покупатель в этой же категории.

Твое задание:
Выведи список пользователей, чьи суммарные траты в конкретной категории выше средних суммарных трат всех пользователей в этой же категории.

Таблицы:

orders (информация о заказах):

order_id (int) — идентификатор заказа;

user_id (int) — идентификатор пользователя;

order_date (date) — дата заказа.

order_items (детализация заказов):

order_id (int) — идентификатор заказа;

product_id (int) — идентификатор товара;

quantity (int) — количество купленного товара.

products (справочник товаров):

product_id (int) — идентификатор товара;

category_name (varchar) — название категории;

price (numeric) — цена за единицу товара.

In [2]:

orders = pd.DataFrame({
    'order_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'user_id': [101, 102, 101, 103, 102, 104, 103, 104],
    'order_date': [
        datetime(2023, 1, 15),
        datetime(2023, 1, 16),
        datetime(2023, 1, 17),
        datetime(2023, 1, 18),
        datetime(2023, 1, 19),
        datetime(2023, 1, 20),
        datetime(2023, 1, 21),
        datetime(2023, 1, 22)
    ]
})
order_items = pd.DataFrame({
    'order_id': [1, 1, 2, 3, 3, 4, 5, 6, 7, 8],
    'product_id': [1001, 1002, 1003, 1001, 1004, 1005, 1006, 1007, 1008, 1009],
    'quantity': [2, 1, 3, 1, 2, 4, 2, 1, 3, 2]
})
products = pd.DataFrame({
    'product_id': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
    'category_name': ['Электроника', 'Электроника', 'Одежда', 'Электроника',
                    'Одежда', 'Продукты', 'Продукты', 'Книги', 'Книги'],
    'price': [15000, 8000, 5000, 12000, 3000, 200, 150, 400, 600]
})

In [9]:
query = """
WITH user_spending AS (
    SELECT
        p.category_name,
        o.user_id,
        SUM(oi.quantity * p.price) AS total_user_category_spent
    FROM orders o
    JOIN order_items oi USING(order_id)
    JOIN products p USING(product_id)
    GROUP BY 1, 2
)
SELECT 
    user_id,
    category_name,
    total_user_category_spent
FROM (
    SELECT *, 
           AVG(total_user_category_spent) OVER(PARTITION BY category_name) as avg_spent_cat
    FROM user_spending
) t
WHERE total_user_category_spent > avg_spent_cat;
"""
result = duckdb.query(query).to_df()
result

   user_id category_name  total_user_category_spent
0      102        Одежда                    15000.0
1      102      Продукты                      400.0

In [22]:
df = orders.merge(order_items).merge(products)
df['summ'] = df['quantity'] * df['price']
df = df.groupby(['category_name', 'user_id'], as_index=False).agg(total_user_category_spent=('summ', 'sum'))
df['avg_spent_cat'] = df.groupby('category_name').total_user_category_spent.transform('mean')
df[df['total_user_category_spent'] > df['avg_spent_cat']][['user_id', 'category_name', 'total_user_category_spent']]

   user_id category_name  total_user_category_spent
2      102        Одежда                      15000
4      102      Продукты                        400

In [ ]:
# 1. Заранее оставляем только нужные колонки
items = order_items[['order_id', 'product_id', 'quantity', 'price']]
prods = products[['product_id', 'category_name']]
ords = orders[['order_id', 'user_id']]

# 2. Считаем стоимость сразу в order_items, чтобы не тащить лишнее через мерджи
items['summ'] = items['quantity'] * items['price']

# 3. Последовательно объединяем и группируем
# Здесь мы избавляемся от таблицы orders как можно раньше
res = items.merge(prods, on='product_id').merge(ords, on='order_id')

# 4. Группировка
df = res.groupby(['category_name', 'user_id'], as_index=False)['summ'].sum()
df.rename(columns={'summ': 'total_user_category_spent'}, inplace=True)

# 5. Оконная функция и фильтр
df['avg_spent_cat'] = df.groupby('category_name')['total_user_category_spent'].transform('mean')
result = df[df['total_user_category_spent'] > df['avg_spent_cat']]

2. Задача: «Retention первого месяца»
Контекст:
Нам нужно понять, насколько качественный трафик пришел к нам в январе 2024 года. Для этого необходимо рассчитать Retention 1-го месяца (какой процент пользователей, зарегистрировавшихся в январе, совершил хотя бы одно действие в феврале).

Твое задание:
Напиши запрос, который выведет одну строку с тремя колонками:

Количество пользователей, зарегистрировавшихся в январе 2024 года.

Количество этих же пользователей, которые совершили хотя бы одно действие в феврале 2024 года.

Процентное соотношение (Retention Rate), округленное до двух знаков после запятой.

Таблицы:

users (регистрации):

user_id (int) — идентификатор пользователя;

signup_date (date) — дата регистрации.

user_actions (активность):

action_id (int) — идентификатор действия;

user_id (int) — идентификатор пользователя;

action_date (date) — дата совершения действия.

Ожидаемый результат:
Колонки: jan_cohort_size, feb_returned_users, retention_rate.

In [14]:
users_data = {
    'user_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'signup_date': [
        '2024-01-05', '2024-01-12', '2024-01-25', '2024-01-30', '2024-01-31', # Январские
        '2023-12-25', '2023-12-30',                                           # Декабрьские
        '2024-02-01', '2024-02-10', '2024-02-15'                              # Февральские
    ]
}
users = pd.DataFrame(users_data)
users['signup_date'] = pd.to_datetime(users['signup_date'])
actions_data = {
    'action_id': range(1, 16),
    'user_id': [
        1, 1, 2, 4, 4,  # Активность январских в январе
        1, 2, 2,        # Активность январских в феврале (наш таргет)
        6, 7,           # Активность декабрьских в январе
        8, 9, 10,       # Активность февральских в феврале
        1, 4            # Активность январских в марте
    ],
    'action_date': [
        '2024-01-06', '2024-01-10', '2024-01-15', '2024-01-30', '2024-01-31',
        '2024-02-05', '2024-02-10', '2024-02-20',
        '2024-01-10', '2024-01-15',
        '2024-02-02', '2024-02-11', '2024-02-16',
        '2024-03-01', '2024-03-05'
    ]
}
user_actions = pd.DataFrame(actions_data)
user_actions['action_date'] = pd.to_datetime(user_actions['action_date'])

In [8]:
query = """
SELECT 
    COUNT(distinct user_id) AS jan_cohort_size,
    COUNT(DISTINCT CASE WHEN action_date >= '2024-02-01' AND action_date < '2024-03-01' THEN user_id END) AS feb_returned_users,
    ROUND(
        COUNT(DISTINCT CASE WHEN action_date >= '2024-02-01' AND action_date < '2024-03-01' THEN user_id END) * 100.0 / 
        NULLIF(COUNT(distinct user_id), 0), 
    2) AS retention_rate
FROM users u
LEFT JOIN user_actions a USING(user_id)
WHERE u.signup_date >= '2024-01-01' AND u.signup_date < '2024-02-01';
"""
result = duckdb.query(query).to_df()
result

   jan_cohort_size  feb_returned_users  retention_rate
0                5                   2            40.0

In [29]:
jan_cohort = users[
    (users['signup_date'] >= '2024-01-01') & 
    (users['signup_date'] < '2024-02-01')
]
jan_cohort_size = jan_cohort['user_id'].nunique()
merged_data = jan_cohort.merge(user_actions, how='left')
feb_returned_users = merged_data[
    (merged_data['action_date'] >= '2024-02-01') & 
    (merged_data['action_date'] < '2024-03-01')
]['user_id'].nunique()
retention_rate = round((feb_returned_users * 100.0 / jan_cohort_size), 2) if jan_cohort_size > 0 else 0
result = pd.DataFrame({
    'jan_cohort_size': [jan_cohort_size],
    'feb_returned_users': [feb_returned_users],
    'retention_rate': [retention_rate]
})
result

   jan_cohort_size  feb_returned_users  retention_rate
0                5                   2            40.0

3. «Топ-3 в категории»
Раз уж ты упомянул, что тебе нравится визуализировать шаги и мы работаем с оконными функциями, давай закрепим этот навык на классической задаче про ранжирование.

Контекст:
Нам нужно понять, какие товары приносят больше всего денег в каждой категории, чтобы вынести их на главную страницу сайта.

Твое задание:
Для каждой категории товаров выведи топ-3 товара по суммарной выручке за всё время.

Таблицы:

order_items:

product_id (int);

quantity (int);

price_at_purchase (numeric) — цена товара в момент покупки.

products:

product_id (int);

product_name (varchar);

category_id (int).

categories:

category_id (int);

category_name (varchar).

Ожидаемый результат:
Колонки: category_name, product_name, total_revenue, rank.
Результат должен быть отсортирован по названию категории, а внутри категории — по убыванию выручки.

In [2]:
categories_data = {
    'category_id': [1, 2, 3, 4],
    'category_name': ['Электроника', 'Одежда', 'Дом и сад', 'Книги']
}
categories = pd.DataFrame(categories_data)
products_data = {
    'product_id': [101, 102, 103, 104, 105, 201, 202, 203, 301, 302, 401],
    'product_name': [
        'Смартфон X', 'Ноутбук Y', 'Наушники Z', 'Зарядка A', 'Планшет B', # Электроника
        'Футболка', 'Джинсы', 'Худи',                                     # Одежда
        'Лампа', 'Диван',                                                # Дом
        'SQL для профи'                                                  # Книги
    ],
    'category_id': [1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4]
}
products = pd.DataFrame(products_data)
order_items_data = {
    'product_id': [
        101, 101, 102, 103, 104, 105, # Электроника: Смартфон (101) и Ноутбук (102) будут лидерами
        201, 202, 202, 203,           # Одежда: Джинсы (202) обгонят футболку
        301, 302, 302,                # Дом: Диван (302) лидер по цене
        401, 401                      # Книги: Всего один товар в категории
    ],
    'quantity': [
        2, 1, 1, 5, 10, 1, 
        3, 2, 1, 1, 
        4, 1, 1, 
        10, 5
    ],
    'price_at_purchase': [
        50000, 50000, 120000, 3000, 500, 30000, 
        1500, 4000, 4000, 6000, 
        2000, 45000, 45000, 
        800, 800
    ]
}
order_items = pd.DataFrame(order_items_data)

In [5]:
query = """
select
    category_name,
    product_name,
    total_revenue,
    rank
from (
    select
        c.category_name,
        p.product_name,
        total_revenue,
        dense_rank() over(partition by c.category_name order by total_revenue desc) as rank
    from 
        categories c join products p using(category_id)
        join (
            select
                product_id,
                sum(quantity * price_at_purchase) as total_revenue
            from order_items
            group by product_id
              ) using(product_id)
      )
where rank <= 3
order by category_name, total_revenue desc
"""
result = duckdb.query(query).to_df()
result

  category_name   product_name  total_revenue  rank
0     Дом и сад          Диван        90000.0     1
1     Дом и сад          Лампа         8000.0     2
2         Книги  SQL для профи        12000.0     1
3        Одежда         Джинсы        12000.0     1
4        Одежда           Худи         6000.0     2
5        Одежда       Футболка         4500.0     3
6   Электроника     Смартфон X       150000.0     1
7   Электроника      Ноутбук Y       120000.0     2
8   Электроника      Планшет B        30000.0     3

In [10]:
order_items['revenue'] = order_items['quantity'] * order_items['price_at_purchase']
df = order_items.groupby('product_id', as_index=False).agg(total_revenue=('revenue', 'sum'))
df = df.merge(products).merge(categories)
df['rank'] = df.groupby('category_id')['total_revenue'].rank(method='dense', ascending=False)
df[df['rank'] <= 3].sort_values(by=['category_name', 'total_revenue'], ascending=[True, False])[['category_name', 'product_name', 'total_revenue', 'rank']]

   category_name   product_name  total_revenue  rank
9      Дом и сад          Диван          90000   1.0
8      Дом и сад          Лампа           8000   2.0
10         Книги  SQL для профи          12000   1.0
6         Одежда         Джинсы          12000   1.0
7         Одежда           Худи           6000   2.0
5         Одежда       Футболка           4500   3.0
0    Электроника     Смартфон X         150000   1.0
1    Электроника      Ноутбук Y         120000   2.0
4    Электроника      Планшет B          30000   3.0

4. «Скорость второго заказа»
Контекст:
Бизнесу важно понимать, как быстро пользователи возвращаются за второй покупкой. Нам нужно вычислить среднее количество дней между первой и второй покупкой для каждого пользователя.

Твое задание:
Для каждого пользователя, у которого было как минимум два заказа, найди разницу в днях между его первым и вторым заказом. В итоге выведи среднее значение этой разницы по всем таким пользователям.

Таблица orders:

order_id (int)

user_id (int)

order_date (date)

Ожидаемый результат:
Одна колонка (или одно значение) — avg_days_to_second_order, округленное до одного знака.

In [13]:
import pandas as pd
orders_data = {
    'order_id': range(1, 15), 
    'user_id': [
        10, 10, 10,  # Юзер 10 (3 заказа)
        20, 20,      # Юзер 20 (2 заказа)
        30,          # Юзер 30 (1 заказ)
        40, 40,      # Юзер 40 (2 заказа)
        50, 50, 50,  # Юзер 50 (3 заказа)
        60,          # Юзер 60 (1 заказ)
        70, 70       # Юзер 70 (2 заказа)
    ],
    'order_date': [
        '2024-01-01', '2024-01-05', '2024-01-10',
        '2024-01-02', '2024-01-15',
        '2024-01-10',
        '2024-01-01', '2024-02-01',
        '2024-02-01', '2024-02-02', '2024-02-15',
        '2024-02-10',
        '2024-03-01', '2024-03-10'
    ]
}
orders = pd.DataFrame(orders_data)
orders['order_date'] = pd.to_datetime(orders['order_date'])
orders = orders.sample(frac=1, random_state=42).reset_index(drop=True)

In [16]:
query = """
with row as(
    select 
        user_id,
        order_date,
        row_number() over(partition by user_id order by order_date) as row_date
    from orders
    where user_id in (select user_id from orders group by user_id)       
)
select 
    avg(r_2.order_date - r_1.order_date) as avg_days_to_second_order
from row r_1 join row r_2 
    on r_1.user_id = r_2.user_id
    and r_1.row_date = 1
    and r_2.row_date = 2
"""
result = duckdb.query(query).to_df()
result

  avg_days_to_second_order
0         11 days 14:24:00

In [18]:
query = """
WITH orders_with_next AS (
    SELECT 
        user_id,
        order_date,
        LEAD(order_date) OVER(PARTITION BY user_id ORDER BY order_date) as next_order_date,
        ROW_NUMBER() OVER(PARTITION BY user_id ORDER BY order_date) as rn
    FROM orders
)
SELECT 
    AVG(next_order_date - order_date) as avg_days_to_second_order
FROM orders_with_next
WHERE rn = 1 AND next_order_date IS NOT NULL;
"""
result = duckdb.query(query).to_df()
result

  avg_days_to_second_order
0         11 days 14:24:00

In [37]:
orders['rank'] = orders.groupby('user_id')['order_date'].rank(method='dense')
df = orders.pivot(
    index='user_id',
    columns='rank',
    values='order_date'
).reset_index()
df = df.iloc[:,[0, 1, 2]].dropna()
avg_days_to_second_order = (df[2.0] - df[1.0]).mean()
result = pd.DataFrame({'avg_days_to_second_order': [avg_days_to_second_order]})
result

  avg_days_to_second_order
0         11 days 14:24:00

In [ ]:
orders_sorted = orders.sort_values(['user_id', 'order_date'])
orders_sorted['prev_date'] = orders_sorted.groupby('user_id')['order_date'].shift(1)
orders_sorted['days_diff'] = (orders_sorted['order_date'] - orders_sorted['prev_date']).dt.days

second_orders_mask = orders_sorted.groupby('user_id').cumcount() == 1
avg_days = orders_sorted[second_orders_mask]['days_diff'].mean()
avg_days

np.float64(11.6)

5. «Накопленная выручка (Running Total)»
Контекст:
Нам нужно построить график того, как росла суммарная выручка нашего сервиса в течение января 2024 года по дням.

Твое задание:
Напиши запрос, который для каждого дня января 2024 года выведет:

Дату.

Выручку за этот конкретный день.

Кумулятивную (накопленную) выручку с начала месяца до текущего дня включительно.

Таблица payments:

payment_id (int)

payment_date (date)

amount (numeric)

Ожидаемый результат:
Колонки: date, daily_revenue, running_total.
Отсортировано по дате.

In [2]:
payments_data = {
    'payment_id': range(1, 16),
    'payment_date': [
        '2024-01-01', '2024-01-01', # Два платежа в один день
        '2024-01-02', 
        '2024-01-04',                # Пропустили 3-е число
        '2024-01-04', 
        '2024-01-05',
        '2024-01-10',                # Большой разрыв
        '2024-01-10',
        '2024-01-11',
        '2024-01-15',
        '2024-01-20',
        '2024-01-25',
        '2024-01-31', '2024-01-31', # Завершаем месяц
        '2024-02-01'                 # Февральский платеж (для проверки фильтрации)
    ],
    'amount': [
        1500.00, 500.00,             # 01.01 сумма 2000
        1200.50, 
        800.00, 
        2200.00, 
        3000.00, 
        5000.00, 
        500.00, 
        1100.00, 
        450.00, 
        990.00, 
        1300.00, 
        2500.00, 500.00,
        10000.00                     # Этот платеж не должен попасть в отчет за январь
    ]
}
payments = pd.DataFrame(payments_data)
payments['payment_date'] = pd.to_datetime(payments['payment_date'])
payments = payments.sample(frac=1, random_state=42).reset_index(drop=True)

In [6]:
payments

    payment_id payment_date   amount
0           10   2024-01-15    450.0
1           12   2024-01-25   1300.0
2            1   2024-01-01   1500.0
3           14   2024-01-31    500.0
4            6   2024-01-05   3000.0
5            9   2024-01-11   1100.0
6            3   2024-01-02   1200.5
7            2   2024-01-01    500.0
8           15   2024-02-01  10000.0
9            5   2024-01-04   2200.0
10           8   2024-01-10    500.0
11          11   2024-01-20    990.0
12          13   2024-01-31   2500.0
13           4   2024-01-04    800.0
14           7   2024-01-10   5000.0

In [15]:
query = """
select 
    payment_date as date,
    daily_revenue,
    sum(daily_revenue) over(order by payment_date) as running_total
from (
    select 
        payment_date,
        sum(amount) as daily_revenue
    from payments
    where payment_date >= '2024-01-01' 
        and payment_date < '2024-02-01'
    group by payment_date)
order by date
"""
result = duckdb.query(query).to_df()
result

        date  daily_revenue  running_total
0 2024-01-01         2000.0         2000.0
1 2024-01-02         1200.5         3200.5
2 2024-01-04         3000.0         6200.5
3 2024-01-05         3000.0         9200.5
4 2024-01-10         5500.0        14700.5
5 2024-01-11         1100.0        15800.5
6 2024-01-15          450.0        16250.5
7 2024-01-20          990.0        17240.5
8 2024-01-25         1300.0        18540.5
9 2024-01-31         3000.0        21540.5

In [16]:
daily_revenue = (
    payments[
        (payments['payment_date'] >= '2024-01-01') & 
        (payments['payment_date'] < '2024-02-01')
    ]
    .groupby('payment_date')['amount']
    .sum()
    .reset_index()
    .rename(columns={'payment_date': 'date', 'amount': 'daily_revenue'})
)
daily_revenue = daily_revenue.sort_values('date')
daily_revenue['running_total'] = daily_revenue['daily_revenue'].cumsum()
daily_revenue

        date  daily_revenue  running_total
0 2024-01-01         2000.0         2000.0
1 2024-01-02         1200.5         3200.5
2 2024-01-04         3000.0         6200.5
3 2024-01-05         3000.0         9200.5
4 2024-01-10         5500.0        14700.5
5 2024-01-11         1100.0        15800.5
6 2024-01-15          450.0        16250.5
7 2024-01-20          990.0        17240.5
8 2024-01-25         1300.0        18540.5
9 2024-01-31         3000.0        21540.5

6. «Максимальная серия (Gaps and Islands)»
Контекст:
Наше приложение для фитнеса хочет награждать пользователей за «ударный режим». Нам нужно найти самую длинную серию дней, когда пользователь тренировался без перерывов.

Твое задание:
Для каждого пользователя найди длину его самой продолжительной беспрерывной серии тренировок (количество дней подряд).

Таблица workouts:

user_id (int) — идентификатор пользователя;

workout_date (date) — дата тренировки.
(Важно: в один день у пользователя может быть несколько тренировок, а может не быть вовсе).

Ожидаемый результат:
Таблица с полями: user_id, max_streak_days.
Отсортируй по убыванию max_streak_days.

In [2]:
workouts_data = {
    'user_id': [
        1, 1, 1, 1, 1, 1,    # Юзер 1 (6 строк)
        2, 2, 2, 2, 2,       # Юзер 2 (5 строк)
        3, 3,                # Юзер 3 (2 строки)
        4, 4                 # Юзер 4 (2 строки)
    ],
    'workout_date': [
        # Юзер 1: серии 3 дня и 2 дня
        '2024-01-01', '2024-01-02', '2024-01-03', 
        '2024-01-05', '2024-01-06', '2024-01-10',
        
        # Юзер 2: серия 4 дня (с дублем 2-го числа)
        '2024-01-01', '2024-01-02', '2024-01-02', '2024-01-03', '2024-01-04',
        
        # Юзер 3: разрыв
        '2024-01-01', '2024-01-15',
        
        # Юзер 4: серия 2 дня
        '2024-01-10', '2024-01-11'
    ]
}
workouts = pd.DataFrame(workouts_data)
workouts['workout_date'] = pd.to_datetime(workouts['workout_date'])
workouts = workouts.sample(frac=1, random_state=42).reset_index(drop=True)

In [15]:
query = """
with agg_work as(
    select user_id, workout_date 
    from workouts
    group by user_id, workout_date
),
t_diff as(
    select 
        user_id,
        workout_date::date - row_number() over(partition by user_id order by workout_date)::integer as diff
    from agg_work
),
t_diff_agg as(
    select
        user_id,
        diff,
        count(*) as count_streak
    from t_diff
    group by 
        user_id, 
        diff
)
select
    user_id,
    max(count_streak) as max_streak_days
from t_diff_agg
group by user_id
order by max_streak_days desc
"""
result = duckdb.query(query).to_df()
result

   user_id  max_streak_days
0        2                4
1        1                3
2        4                2
3        3                1

In [24]:
query = """
with t_dif as(
    select
        user_id,
        workout_date::date - (row_number() over(partition by user_id order by workout_date))::integer as dif
    from (
        select user_id, workout_date from workouts group by user_id, workout_date)
)
select user_id, max(count_streak) as max_streak_days from (
    select user_id, count(*) as count_streak from t_dif group by user_id, dif
)
group by user_id
order by max_streak_days desc
"""
result = duckdb.query(query).to_df()
result

   user_id  max_streak_days
0        2                4
1        1                3
2        4                2
3        3                1

In [13]:
df = workouts[['user_id', 'workout_date']].drop_duplicates()
df = df.sort_values(['user_id', 'workout_date'])
df['rn'] = df.groupby('user_id').cumcount()
df['dif'] = df['workout_date'] - pd.to_timedelta(df['rn'], unit='D')
streaks = df.groupby(['user_id', 'dif']).size().reset_index(name='count_streak')
streaks.groupby('user_id')['count_streak'].max().reset_index(name='max_streak_days').sort_values('max_streak_days', ascending=False)

   user_id  max_streak_days
1        2                4
0        1                3
3        4                2
2        3                1

7. «Дыры в данных» (Усложняем)
Ты просил уровень посложнее — давай добавим в задачу элемент, который часто встречается в реальности, но о котором забывают на курсах.

Контекст:
Нам нужно посчитать DAU (Daily Active Users) и скользящее среднее DAU за 7 дней для нашего продукта за первую половину марта 2024 года.

Нюанс:
В таблице логов фиксируются только те дни, когда пользователи были активны. Но для корректного графика и среднего нам нужны все дни периода (с 1 по 15 марта), даже если в какой-то из дней никто не зашел (в этом случае DAU должен быть 0).

Твое задание:
Напиши запрос, который выведет:

Дату (все дни с 2024-03-01 по 2024-03-15 включительно).

DAU (количество уникальных пользователей) в этот день.

7-дневное скользящее среднее DAU (среднее значение DAU за текущий день и 6 предыдущих).

Таблица activity:

user_id (int);

activity_date (date).

Ожидаемый результат:
Колонки: date, dau, rolling_avg_7d.

Критерии:

В результате должны быть все 15 дней (без пропусков).

Если данных за день нет — DAU должен быть 0.

Оптимальность использования оконных функций.

In [21]:
activity_data = {
    'user_id': [
        101, 102, 103,      # 01 марта: 3 юзера
        101,                # 02 марта: 1 юзер
        101, 104,           # 03 марта: 2 юзера
        # 04 марта: ПУСТО (дыра)
        # 05 марта: ПУСТО (дыра)
        105, 106, 107, 108, # 06 марта: 4 юзера
        101,                # 07 марта: 1 юзер
        102, 103,           # 08 марта: 2 юзера
        101, 105, 110,      # 09 марта: 3 юзера
        111,                # 10 марта: 1 юзер
        # 11 марта: ПУСТО (дыра)
        101, 102,           # 12 марта: 2 юзера
        103, 104, 105,      # 13 марта: 3 юзера
        101,                # 14 марта: 1 юзер
        108, 109, 110       # 15 марта: 3 юзера
    ],
    'activity_date': [
        '2024-03-01', '2024-03-01', '2024-03-01',
        '2024-03-02',
        '2024-03-03', '2024-03-03',
        '2024-03-06', '2024-03-06', '2024-03-06', '2024-03-06',
        '2024-03-07',
        '2024-03-08', '2024-03-08',
        '2024-03-09', '2024-03-09', '2024-03-09',
        '2024-03-10',
        '2024-03-12', '2024-03-12',
        '2024-03-13', '2024-03-13', '2024-03-13',
        '2024-03-14',
        '2024-03-15', '2024-03-15', '2024-03-15'
    ]
}
activity = pd.DataFrame(activity_data)
activity['activity_date'] = pd.to_datetime(activity['activity_date'])
calendar = pd.DataFrame({
    'date': pd.date_range(start='2024-03-01', end='2024-03-15')
})

In [ ]:
query = """
with t as(
    select 
        date, 
        count(distinct user_id) as dau
    from activity a right join (
    SELECT CAST(day AS DATE) as date
    FROM range(
        '2024-03-01'::DATE, 
        '2024-03-16'::DATE, -- В range правая граница НЕ включается, поэтому берем +1 день
        INTERVAL 1 DAY
    ) AS t(day)
    ) y on a.activity_date = y.date
    group by date
)
select
    date,
    dau,
    round(avg(dau) over(order by date rows between 6 preceding and current row), 2) as rolling_avg_7d
from t
"""
result = duckdb.query(query).to_df()
result

         date  dau  rolling_avg_7d
0  2024-03-01    3            3.00
1  2024-03-02    1            2.00
2  2024-03-03    2            2.00
3  2024-03-04    0            1.50
4  2024-03-05    0            1.20
5  2024-03-06    4            1.67
6  2024-03-07    1            1.57
7  2024-03-08    2            1.43
8  2024-03-09    3            1.71
9  2024-03-10    1            1.57
10 2024-03-11    0            1.57
11 2024-03-12    2            1.86
12 2024-03-13    3            1.71
13 2024-03-14    1            1.71
14 2024-03-15    3            1.86

In [21]:
query = """
with tab_cal as(
    SELECT CAST(day AS DATE) as date
    FROM range(
        '2024-03-01'::DATE, 
        '2024-03-16'::DATE, -- В range правая граница НЕ включается, поэтому берем +1 день
        INTERVAL 1 DAY
    ) AS t(day)
),
agg_act as(
    select
        activity_date as date, 
        count(distinct user_id) as dau
    from activity
    group by date
),
tab_dau as(
    select 
        date,
        coalesce(dau, 0) as dau,
    from tab_cal left join agg_act using(date)
)
select 
    date,
    dau,
    round(avg(dau) over(order by date rows between 6 preceding and current row), 2) as rolling_avg_7d
from tab_dau
order by date
"""
result = duckdb.query(query).to_df()
result

         date  dau  rolling_avg_7d
0  2024-03-01    3            3.00
1  2024-03-02    1            2.00
2  2024-03-03    2            2.00
3  2024-03-04    0            1.50
4  2024-03-05    0            1.20
5  2024-03-06    4            1.67
6  2024-03-07    1            1.57
7  2024-03-08    2            1.43
8  2024-03-09    3            1.71
9  2024-03-10    1            1.57
10 2024-03-11    0            1.57
11 2024-03-12    2            1.86
12 2024-03-13    3            1.71
13 2024-03-14    1            1.71
14 2024-03-15    3            1.86

In [36]:
date_list = pd.date_range(start='2024-03-01', periods=15).strftime('%Y-%m-%d').tolist()
cal = pd.DataFrame(date_list, columns=['date'])
cal['date'] = pd.to_datetime(cal['date'])
df = activity.rename(columns={'activity_date': 'date'}).groupby('date', as_index=False).agg(dau = ('user_id', 'count')).merge(cal, how='right')
df['dau'] = df['dau'].fillna(0)
df['rolling_avg_7d'] = df['dau'].rolling(window=7, min_periods=1).mean().round(2)
df.sort_values(['date'])

         date  dau  rolling_avg_7d
0  2024-03-01  3.0            3.00
1  2024-03-02  1.0            2.00
2  2024-03-03  2.0            2.00
3  2024-03-04  0.0            1.50
4  2024-03-05  0.0            1.20
5  2024-03-06  4.0            1.67
6  2024-03-07  1.0            1.57
7  2024-03-08  2.0            1.43
8  2024-03-09  3.0            1.71
9  2024-03-10  1.0            1.57
10 2024-03-11  0.0            1.57
11 2024-03-12  2.0            1.86
12 2024-03-13  3.0            1.71
13 2024-03-14  1.0            1.71
14 2024-03-15  3.0            1.86

8. «Эффективность маркетинга (LTV первого касания)»
Контекст:
У нас есть данные о заказах и о том, из какого рекламного канала пришел пользователь (первое касание). Нам нужно сравнить каналы по их эффективности за первые 30 дней жизни пользователя.

Твое задание:
Для каждого рекламного канала (utm_source) посчитай:

Количество уникальных пользователей, пришедших из этого канала.

Суммарную выручку, которую эти пользователи принесли в течение своих первых 30 дней с момента регистрации.

ARPU (Average Revenue Per User) для этого канала за те же 30 дней.

Таблицы:

users:

user_id (int);

signup_date (date);

utm_source (varchar) — канал привлечения (google, facebook, organic и т.д.).

orders:

order_id (int);

user_id (int);

order_date (date);

amount (numeric).

Ожидаемый результат:
Колонки: utm_source, total_users, revenue_30d, arpu_30d.

Критерий сложности:
Важно правильно ограничить выручку для каждого пользователя индивидуально: учитываются только те заказы, которые были сделаны в интервале [signup_date; signup_date + 30 дней].

In [8]:
users_data = {
    'user_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'signup_date': [
        '2024-01-01', '2024-01-01', # Google
        '2024-01-10', '2024-01-12', # Facebook
        '2024-01-15', '2024-01-20', # Organic
        '2024-02-01', '2024-02-01'  # Google, Facebook
    ],
    'utm_source': [
        'google', 'google', 
        'facebook', 'facebook', 
        'organic', 'organic', 
        'google', 'facebook'
    ]
}
users = pd.DataFrame(users_data)
users['signup_date'] = pd.to_datetime(users['signup_date'])
orders_data = {
    'order_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'user_id': [
        1, 1,    # Юзер 1 (входят)
        2,       # Юзер 2 (НЕ входит, > 30 дней)
        3,       # Юзер 3 (входит)
        4,       # Юзер 4 (входит)
        4,       # Юзер 4 (НЕ входит, > 30 дней)
        5,       # Юзер 5 (входит)
        7,       # Юзер 7 (входит)
        1,       # Юзер 1 (еще один, входит)
        3        # Юзер 3 (НЕ входит, > 30 дней)
    ],
    'order_date': [
        '2024-01-05', '2024-01-25',
        '2024-02-15', 
        '2024-02-05', 
        '2024-02-10', 
        '2024-02-20',
        '2024-01-20',
        '2024-02-05',
        '2024-01-10',
        '2024-03-15'
    ],
    'amount': [
        1000, 1500, 
        5000, 
        2000, 
        1500, 
        3000,
        800,
        1200,
        500,
        4000
    ]
}

orders = pd.DataFrame(orders_data)
orders['order_date'] = pd.to_datetime(orders['order_date'])

In [41]:
query = """
select 
    utm_source,
    count(distinct u.user_id) as total_users,
    sum(amount) as revenue_30d,
    round(sum(amount) / count(distinct u.user_id), 2) as arpu_30d
from users u left join orders o 
    on u.user_id = o.user_id
    and o.order_date::date <= u.signup_date::date + 30 
group by utm_source
"""
result = duckdb.query(query).to_df()
result

  utm_source  total_users  revenue_30d  arpu_30d
0     google            3       4200.0   1400.00
1   facebook            3       3500.0   1166.67
2    organic            2        800.0    400.00

In [ ]:
query = """
WITH user_30d_revenue AS (
    SELECT 
        u.utm_source,
        u.user_id,
        COALESCE(orders_agg.total_amount, 0) as revenue
    FROM users u
    LEFT JOIN LATERAL (
        SELECT SUM(amount) as total_amount
        FROM orders o
        WHERE o.user_id = u.user_id
          AND o.order_date <= u.signup_date + INTERVAL '30 days'
    ) orders_agg ON TRUE
)
SELECT 
    utm_source,
    COUNT(user_id) as total_users, -- Теперь DISTINCT не нужен, юзеров не "раздуло"
    SUM(revenue) as revenue_30d,
    ROUND(AVG(revenue), 2) as arpu_30d -- AVG по всем, включая нули
FROM user_30d_revenue
GROUP BY 1;
"""
result = duckdb.query(query).to_df()
result

  utm_source  total_users  revenue_30d  arpu_30d
0     google            3       4200.0   1400.00
1   facebook            3       3500.0   1166.67
2    organic            2        800.0    400.00

In [13]:
df = users.merge(orders, how='left')
df['amount'] = df['amount'].fillna(0)
df = df[df['order_date'] <= df['signup_date'] + pd.Timedelta(days=30)]
df.groupby('utm_source', as_index=False).agg(total_users=('user_id', 'nunique'), revenue_30d=('amount', 'sum'))

  utm_source  total_users  revenue_30d
0   facebook            2       3500.0
1     google            2       4200.0
2    organic            1        800.0

In [16]:
df = pd.merge(users, orders, on='user_id', how='left')
mask = (df['order_date'] <= df['signup_date'] + pd.Timedelta(days=30))
df.loc[~mask, 'amount'] = 0
user_revenue = df.groupby(['utm_source', 'user_id'])['amount'].sum().reset_index()
user_revenue.rename(columns={'amount': 'revenue'}, inplace=True)
result = user_revenue.groupby('utm_source').agg(
    total_users=('user_id', 'count'),
    revenue_30d=('revenue', 'sum'),
    arpu_30d=('revenue', 'mean')
).reset_index()
result['arpu_30d'] = result['arpu_30d'].round(2)
result

  utm_source  total_users  revenue_30d  arpu_30d
0   facebook            3       3500.0   1166.67
1     google            3       4200.0   1400.00
2    organic            2        800.0    400.00

9. «Анализ поведения активных новичков»
Контекст:
Нам нужно исследовать поведение «активных новичков» в приложении для онлайн-кинотеатра. Нас интересуют те, кто быстро втянулся в просмотры, и мы хотим понять, с какого именно фильма начался их путь.

Твое задание:

Найди всех пользователей, которые зарегистрировались в январе 2024 года.

Среди них оставь только тех, у кого есть хотя бы 5 завершенных просмотров (статус finished). Для этого используй EXISTS.

Для каждого такого пользователя выведи:

user_id

signup_date

Название самого первого фильма, который он посмотрел (независимо от статуса завершения). Для этого используй LATERAL.

Дату этого первого просмотра.

Таблицы:

users:

user_id (int);

signup_date (date).

views:

view_id (int);

user_id (int);

movie_title (varchar);

view_date (timestamp);

status (varchar) — может быть 'finished', 'stopped', 'started'.

Ожидаемый результат:
Колонки: user_id, signup_date, first_movie_title, first_view_date.

Критерии проверки:

EXISTS: Должен эффективно отсекать пользователей, не соответствующих критерию активности (5+ завершенных просмотров).

LATERAL: Должен находить ровно одну строку (самый первый просмотр) для каждого прошедшего фильтр пользователя.

Оптимизация: Код должен быть написан так, чтобы база не делала лишних тяжелых группировок, если это можно решить через коррелированные подзапросы.

In [2]:
users_data = {
    'user_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'signup_date': [
        '2024-01-05', '2024-01-10', '2024-01-15', '2024-01-20', # Январские
        '2024-01-25',                                           # Январский
        '2023-12-20', '2023-12-30',                             # Декабрьские (отсеются)
        '2024-02-01'                                            # Февральский (отсеется)
    ]
}
users = pd.DataFrame(users_data)
users['signup_date'] = pd.to_datetime(users['signup_date'])
views_data = {
    'view_id': range(1, 23),
    'user_id': [
        1, 1, 1, 1, 1,       # Юзер 1: 5 просмотров, все 'finished'. Первый фильм — 'Матрица'
        2, 2, 2, 2, 2, 2,    # Юзер 2: 6 просмотров, 5 'finished'. Первый фильм — 'Интерстеллар' (started)
        3, 3, 3,             # Юзер 3: 3 просмотра (мало для EXISTS)
        4, 4, 4, 4, 4,       # Юзер 4: 5 просмотров, но только 3 'finished' (отсеется)
        6,                   # Юзер 6: 1 просмотр (декабрьский юзер)
        7, 8                 # Остальные
    ],
    'movie_title': [
        'Матрица', 'Начало', 'Тьма', 'Ведьмак', 'Шерлок',
        'Интерстеллар', 'Дюна', 'Гладиатор', 'Чужой', 'Троя', 'Семь',
        'Клаус', 'Душа', 'Вверх',
        'Леон', 'Жара', 'Драйв', 'Пленницы', 'Враг',
        'Офис', 'Друзья', 'Корона'
    ],
    'view_date': [
        '2024-01-06 10:00', '2024-01-07 12:00', '2024-01-08 15:00', '2024-01-09 18:00', '2024-01-10 20:00',
        '2024-01-11 09:00', '2024-01-12 11:00', '2024-01-13 14:00', '2024-01-14 16:00', '2024-01-15 19:00', '2024-01-16 21:00',
        '2024-01-16 10:00', '2024-01-17 12:00', '2024-01-18 14:00',
        '2024-01-21 08:00', '2024-01-22 10:00', '2024-01-23 13:00', '2024-01-24 15:00', '2024-01-25 17:00',
        '2023-12-21 20:00', '2023-12-31 22:00', '2024-02-02 10:00'
    ],
    'status': [
        'finished', 'finished', 'finished', 'finished', 'finished', # Юзер 1
        'started', 'finished', 'finished', 'finished', 'finished', 'finished', # Юзер 2
        'finished', 'finished', 'finished', # Юзер 3
        'started', 'stopped', 'finished', 'finished', 'finished', # Юзер 4
        'finished', 'finished', 'finished'
    ]
}

views = pd.DataFrame(views_data)
views['view_date'] = pd.to_datetime(views['view_date'])

In [ ]:
query = """
with five_finished_table as(
    select
        u.user_id,
        u.signup_date
    from users u
    where exists(
        select 1
        from views v
        where u.user_id = v.user_id
            and v.status = 'finished'
        group by user_id
        having count(status) >= 5)
)
select 
    f.user_id,
    f.signup_date,
    
"""
result = duckdb.query(query).to_df()
result

   user_id signup_date
0        1  2024-01-05
1        2  2024-01-10

In [3]:
query = """
SELECT 
    u.user_id, 
    u.signup_date, 
    v_first.movie_title AS first_movie_title, 
    v_first.view_date AS first_view_date
FROM users u
-- LATERAL находит ровно одну (первую) строку для каждого юзера
CROSS JOIN LATERAL (
    SELECT movie_title, view_date
    FROM views v
    WHERE v.user_id = u.user_id
    ORDER BY view_date ASC
    LIMIT 1
) v_first
WHERE u.signup_date >= '2024-01-01' AND u.signup_date < '2024-02-01'
-- EXISTS проверяет наличие 5+ завершенных просмотров
AND EXISTS (
    SELECT 1 
    FROM views v
    WHERE v.user_id = u.user_id AND v.status = 'finished'
    HAVING COUNT(*) >= 5
);
"""
result = duckdb.query(query).to_df()
result

   user_id signup_date first_movie_title     first_view_date
0        1  2024-01-05           Матрица 2024-01-06 10:00:00
1        2  2024-01-10      Интерстеллар 2024-01-11 09:00:00

10. «Звездные авторы и их новинки»
Контекст:
У нас есть библиотека. Нам нужен список авторов, у которых есть хотя бы одна книга, и для каждого такого автора мы хотим увидеть название его самой последней выпущенной книги.

Таблицы:

authors: auth_id, auth_name

books: book_id, auth_id, title, release_date

In [31]:
authors_data = {
    'auth_id': [1, 2, 3, 4, 5, 6],
    'auth_name': [
        'Айзек Азимов', 
        'Стивен Кинг', 
        'Фрэнк Герберт', 
        'Терри Пратчетт', 
        'Нил Гейман',
        'Автор Без Книг' # Проверит фильтрацию (должен отсеяться)
    ]
}
authors = pd.DataFrame(authors_data)
books_data = {
    'book_id': range(101, 110), # Генерирует 9 ID: от 101 до 109
    'auth_id': [
        1, 1, 1,  # Азимов (3 книги)
        2, 2,     # Кинг (2 книги)
        3,        # Герберт (1 книга)
        4, 4,     # Пратчетт (2 книги, одна дата)
        5         # Гейман (1 книга)
    ],
    'title': [
        'Основание', 'Академия и Империя', 'Второе Основание',
        'Сияние', 'Институт',
        'Дюна',
        'Цвет волшебства', 'Безумная звезда',
        'Американские боги'
    ],
    'release_date': [
        '1951-06-01', '1952-05-01', '1953-06-01',
        '1977-01-28', '2019-09-10',
        '1965-08-01',
        '1983-11-24', '1983-11-24',
        '2001-06-19'
    ]
}
books = pd.DataFrame(books_data)
books['release_date'] = pd.to_datetime(books['release_date'])
books = books.sample(frac=1, random_state=42).reset_index(drop=True)

In [21]:
query = """
select
    a.auth_name,
    b_latest.title
from authors a
cross join lateral(
    select title
    from books b
    where a.auth_id = b.auth_id
    order by release_date desc
    limit 1) b_latest
where exists (
    select 1
    from books b
    where a.auth_id = b.auth_id)
"""
result = duckdb.query(query).to_df()
result

        auth_name              title
0    Айзек Азимов   Второе Основание
1     Стивен Кинг           Институт
2   Фрэнк Герберт               Дюна
3  Терри Пратчетт    Безумная звезда
4      Нил Гейман  Американские боги

In [ ]:
books['rank'] = books.groupby('auth_id')['release_date'].rank(method='dense', ascending=False)
books[books['rank'] == 1].merge(authors)[['auth_name', 'title']]

        auth_name              title
0  Терри Пратчетт    Безумная звезда
1   Фрэнк Герберт               Дюна
2      Нил Гейман  Американские боги
3    Айзек Азимов   Второе Основание
4     Стивен Кинг           Институт
5  Терри Пратчетт    Цвет волшебства

In [43]:
top_books = books[books.groupby('auth_id')['release_date'].rank(method='dense', ascending=False) == 1]
top_books[['auth_id', 'title']].merge(authors[['auth_id', 'auth_name']], on='auth_id')[['auth_name', 'title']]

        auth_name              title
0  Терри Пратчетт    Безумная звезда
1   Фрэнк Герберт               Дюна
2      Нил Гейман  Американские боги
3    Айзек Азимов   Второе Основание
4     Стивен Кинг           Институт
5  Терри Пратчетт    Цвет волшебства

11. Задача: «Сотрудники и их главные задачи»
Контекст:
В корпоративном трекере задач нам нужно настроить дашборд, который показывает, над чем сейчас важнее всего работают наши люди.

Таблицы:

employees: emp_id, name

tasks: task_id, emp_id, task_title, priority (целое число; чем больше число, тем выше приоритет задачи, например, 5 — критическая, 1 — низкий приоритет).

Твое задание:
Выведи имя сотрудника (name) и название его самой приоритетной задачи (task_title).

В список должны попасть только те сотрудники, у которых есть хотя бы одна задача (используй EXISTS).

Для каждого сотрудника нужно вывести ровно одну задачу с самым высоким числом в поле priority (используй CROSS JOIN LATERAL).

In [44]:
employees_data = {
    'emp_id': [1, 2, 3, 4, 5, 6],
    'name': [
        'Иван Иванов', 
        'Анна Петрова', 
        'Сергей Сидоров', 
        'Елена Кузнецова', 
        'Михаил Попов',
        'Ольга Соколова'  # Сотрудник без задач (должен отсеяться)
    ]
}
employees = pd.DataFrame(employees_data)
tasks_data = {
    'task_id': range(101, 110), # Генерирует 9 ID: от 101 до 109
    'emp_id': [
        1, 1, 1,  # Иван (3 задачи)
        2, 2,     # Анна (2 задачи)
        3,        # Сергей (1 задача)
        4, 4,     # Елена (2 задачи, одинаковый приоритет)
        5         # Михаил (1 задача)
    ],
    'task_title': [
        'Починить баг с авторизацией', 'Написать тесты', 'Обновить документацию',
        'Разработать дизайн главной', 'Согласовать макеты',
        'Настроить CI/CD пайплайн',
        'Подготовить квартальный отчет', 'Собрать метрики для презентации',
        'Провести аудит безопасности'
    ],
    'priority': [
        5, 3, 1,  # У Ивана топ-1 — баг с приоритетом 5
        4, 2,     # У Анны топ-1 — дизайн с приоритетом 4
        3,        # У Сергея единственная задача с приоритетом 3
        5, 5,     # У Елены две критические задачи (тест на дубли приоритетов)
        2         # У Михаила единственная задача с приоритетом 2
    ]
}
tasks = pd.DataFrame(tasks_data)
tasks = tasks.sample(frac=1, random_state=42).reset_index(drop=True)

In [28]:
query = """
select
    e.name,
    most_prior.task_title
from employees e
cross join lateral(
    select task_title
    from tasks t
    where e.emp_id = t.emp_id
    order by priority desc
    limit 1) most_prior
where exists(
    select 1
    from tasks t
    where e.emp_id = t.emp_id)
"""
result = duckdb.query(query).to_df()
result

              name                       task_title
0      Иван Иванов      Починить баг с авторизацией
1     Анна Петрова       Разработать дизайн главной
2   Сергей Сидоров         Настроить CI/CD пайплайн
3  Елена Кузнецова  Собрать метрики для презентации
4     Михаил Попов      Провести аудит безопасности

In [46]:
df = tasks[tasks.groupby('emp_id')['priority'].rank(method='dense', ascending=False) == 1]
df[['emp_id', 'task_title']].merge(employees)[['name', 'task_title']]

              name                       task_title
0  Елена Кузнецова  Собрать метрики для презентации
1   Сергей Сидоров         Настроить CI/CD пайплайн
2      Иван Иванов      Починить баг с авторизацией
3     Михаил Попов      Провести аудит безопасности
4     Анна Петрова       Разработать дизайн главной
5  Елена Кузнецова    Подготовить квартальный отчет

12. «Атрибуция первой покупки»
Контекст:
Маркетологам нужно понять путь пользователя к конверсии. Нам важно сопоставить первую сессию (откуда узнал о нас) и сессию, которая привела к первой покупке.

Таблицы:

users:

user_id (int)

sessions:

user_id (int)

source (varchar) — рекламный канал (например, 'google', 'facebook', 'organic')

created_at (timestamp) — время начала сессии

orders:

user_id (int)

order_id (int)

created_at (timestamp) — время совершения заказа

Твое задание:
Для каждого пользователя, который совершил хотя бы один заказ, выведи одну строку, содержащую:

user_id.

first_channel — название source его самой первой сессии в истории.

conversion_channel — название source той сессии, которая была последней перед (или в момент) его самого первого заказа.

Ожидаемый результат:
Колонки: user_id, first_channel, conversion_channel.

In [15]:
import pandas as pd

# 1. Таблица пользователей (5 строк)
users_data = {
    'user_id': [1, 2, 3, 4, 5]
}
users = pd.DataFrame(users_data)

# 2. Таблица сессий (12 строк во всех списках)
sessions_data = {
    'user_id': [
        1, 1, 1,     # Юзер 1: пришел с google, перед покупкой перешел с facebook
        2, 2,        # Юзер 2: одна сессия с organic, с нее же и купил
        3, 3, 3,     # Юзер 3: первый раз с yandex, потом vk, перед покупкой — telegram
        4, 4,        # Юзер 4: много сессий, но заказов нет (должен отсеяться)
        5, 5         # Юзер 5: пришел с google, заказ сделал строго в момент сессии из vk
    ],
    'source': [
        'google', 'email', 'facebook',
        'organic', 'organic',
        'yandex', 'vk', 'telegram',
        'google', 'facebook',
        'google', 'vk'
    ],
    'created_at': [
        '2024-01-01 10:00:00', '2024-01-02 14:00:00', '2024-01-03 11:00:00',
        '2024-01-05 18:20:00', '2024-01-06 19:00:00',
        '2024-01-10 12:00:00', '2024-01-11 15:30:00', '2024-01-12 17:45:00',
        '2024-01-15 09:00:00', '2024-01-16 13:00:00',
        '2024-01-20 10:00:00', '2024-01-20 15:00:00'
    ]
}
sessions = pd.DataFrame(sessions_data)
sessions['created_at'] = pd.to_datetime(sessions['created_at'])

# 3. Таблица заказов (5 строк во всех списках)
orders_data = {
    'user_id': [
        1, 1,        # Юзер 1: два заказа. Нас интересует только первый (01-03)
        2,           # Юзер 2: один заказ
        3,           # Юзер 3: один заказ
        5            # Юзер 5: один заказ совпадает по времени со второй сессией
    ],
    'order_id': [101, 102, 103, 104, 105],
    'created_at': [
        '2024-01-03 11:15:00', '2024-01-05 16:00:00', # Юзер 1 (первый заказ 3 января)
        '2024-01-05 18:30:00',                         # Юзер 2 (заказ через 10 минут после 1-й сессии)
        '2024-01-12 18:00:00',                         # Юзер 3 (заказ после сессии из telegram)
        '2024-01-20 15:00:00'                          # Юзер 5 (заказ ровно в момент сессии vk)
    ]
}
orders = pd.DataFrame(orders_data)
orders['created_at'] = pd.to_datetime(orders['orders_created_at'] if 'orders_created_at' in orders_data else orders_data['created_at'])

# Перемешаем сессии и заказы, чтобы сымитировать реальное поведение СУБД
sessions = sessions.sample(frac=1, random_state=42).reset_index(drop=True)
orders = orders.sample(frac=1, random_state=42).reset_index(drop=True)

print("Все датафреймы успешно созданы и сбалансированы!")
print(f"Пользователей: {len(users)}, Сессий: {len(sessions)}, Заказов: {len(orders)}")

Все датафреймы успешно созданы и сбалансированы!
Пользователей: 5, Сессий: 12, Заказов: 5

In [25]:
query = """
with t as(
    select 
        u.user_id,
        z.order_id as first_order_id,
        z.created_at as created_first_order
    from users u
    cross join lateral(
        select 
            order_id,
            created_at
        from orders o
        where u.user_id = o.user_id
        order by created_at
        limit 1) z
),
j as(
    select 
        t.user_id,
        t.first_order_id,
        t.created_first_order,
        s.source,
        s.created_at as created_session,
        row_number() over(partition by t.user_id order by s.created_at desc) as row_session
    from t join sessions s
        on t.user_id = s.user_id
        and t.created_first_order >= s.created_at
    order by t.user_id, first_order_id
),
o as(
    select 
        u.user_id,
        y.source as first_channel
    from users u
    cross join lateral(
        select source
        from sessions s
        where u.user_id = s.user_id
        order by created_at
        limit 1) y
    where exists(
        select 1
        from orders o
        where u.user_id = o.user_id)
)
select 
    o.user_id,
    o.first_channel,
    j.source as conversion_channel
from o join j 
    on o.user_id = j.user_id
    and j.row_session = 1
"""
result = duckdb.query(query).to_df()
result

   user_id first_channel conversion_channel
0        1        google           facebook
1        2       organic            organic
2        3        yandex           telegram
3        5        google                 vk

In [4]:
query = """
SELECT 
    u.user_id,
    s_first.source AS first_channel,
    s_conv.source AS conversion_channel
FROM users u
-- 1. Находим самую первую сессию пользователя
CROSS JOIN LATERAL (
    SELECT source
    FROM sessions s
    WHERE s.user_id = u.user_id
    ORDER BY created_at ASC
    LIMIT 1
) s_first
-- 2. Находим первый заказ. CROSS JOIN сразу отсечет пользователей без заказов (замена EXISTS)
CROSS JOIN LATERAL (
    SELECT created_at AS first_order_at
    FROM orders o
    WHERE o.user_id = u.user_id
    ORDER BY created_at ASC
    LIMIT 1
) o_first
-- 3. Находим ПОСЛЕДНЮЮ сессию ПЕРЕД этим первым заказом
CROSS JOIN LATERAL (
    SELECT source
    FROM sessions s
    WHERE s.user_id = u.user_id
      AND s.created_at <= o_first.first_order_at -- подзапрос "видит" данные из o_first!
    ORDER BY created_at DESC
    LIMIT 1
) s_conv;
"""
result = duckdb.query(query).to_df()
result

   user_id first_channel conversion_channel
0        1        google           facebook
1        2       organic            organic
2        3        yandex           telegram
3        5        google                 vk

In [37]:
orders_sorted = orders.sort_values('created_at')
sessions_sorted = sessions.sort_values('created_at')
orders_with_source = pd.merge_asof(
    orders_sorted, 
    sessions_sorted[['user_id', 'created_at', 'source']], 
    on='created_at', 
    by='user_id', 
    direction='backward'
)
first_order_session = orders_with_source.sort_values(['user_id', 'created_at']).drop_duplicates(subset=['user_id'], keep='first').rename(columns={'source': 'conversion_channel'})[['user_id', 'conversion_channel']]
first_sessions = sessions.sort_values(['user_id', 'created_at']).drop_duplicates(subset=['user_id'], keep='first').rename(columns={'source': 'first_channel'})[['user_id', 'first_channel']]
first_sessions.merge(first_order_session)

   user_id first_channel conversion_channel
0        1        google           facebook
1        2       organic            organic
2        3        yandex           telegram
3        5        google                 vk

13. Каверзная оконка (Тема: Gaps & Islands)
Это абсолютный хит собеседований. На ней проверяют не просто знание синтаксиса, а умение мыслить нестандартно, когда стандартные LEAD/LAG не помогают напрямую.

Контекст
Продуктовая метрика Daily Active Users (DAU) важна, но еще важнее — регулярность. Нам нужно найти пользователей, которые сформировали привычку пользоваться сервисом.

Таблица
user_logins:

user_id (int)

login_date (date) — дата, когда пользователь зашел в приложение. (Учти, что один пользователь может зайти в один и тот же день несколько раз, но нам важен сам факт дня).

Твое задание
Для каждого пользователя найди длину его самого длинного стрика (серии) непрерывных дней, когда он заходил в приложение без перерывов.

Ожидаемый результат
Колонки: user_id, max_streak (максимальное кол-во дней подряд).

In [2]:
import pandas as pd

# Таблица логинов (строго по 16 элементов в каждом списке)
user_logins_data = {
    'user_id': [
        1, 1, 1, 1, 1,   # Юзер 1: Серия 3 дня, перерыв, серия 2 дня. Max стрик = 3.
        2, 2, 2, 2, 2,   # Юзер 2: Повторные входы + серия 4 дня. Max стрик = 4.
        3, 3,            # Юзер 3: Два входа с большим перерывом. Max стрик = 1.
        4, 4, 4, 4       # Юзер 4: Идеальный стрик 4 дня подряд. Max стрик = 4.
    ],
    'login_date': [
        # Юзер 1
        '2024-01-01', '2024-01-02', '2024-01-03', # Стрик 1 (3 дня)
        '2024-01-05', '2024-01-06',               # Стрик 2 (2 дня)
        
        # Юзер 2
        '2024-01-10', 
        '2024-01-11', '2024-01-11',               # Дубликат (зашел дважды в один день)
        '2024-01-12', '2024-01-13',               # Итого стрик (4 дня)
        
        # Юзер 3
        '2024-01-01', '2024-01-10',               # Два разрозненных дня
        
        # Юзер 4
        '2024-01-15', '2024-01-16', '2024-01-17', '2024-01-18' # Чистый стрик (4 дня)
    ]
}

user_logins = pd.DataFrame(user_logins_data)
user_logins['login_date'] = pd.to_datetime(user_logins['login_date'])

# Перемешиваем строки для симуляции реального лога из базы данных
user_logins = user_logins.sample(frac=1, random_state=42).reset_index(drop=True)

print("Таблица user_logins успешно создана!")
print(f"Всего строк в логе: {len(user_logins)}")

Таблица user_logins успешно создана!
Всего строк в логе: 16

In [3]:
query = """
with t_dif as(
    select 
        user_id,
        login_date::date - (row_number() over(partition by user_id order by login_date))::integer as dif
    from(
        select user_id, login_date from user_logins group by user_id, login_date)
)
select
    user_id, 
    max(count_streak) as max_streak
from(
    select user_id, dif, count(*) as count_streak from t_dif group by user_id, dif)
group by user_id
"""
result = duckdb.query(query).to_df()
result

   user_id  max_streak
0        4           4
1        3           1
2        2           4
3        1           3

In [5]:
user_logins

    user_id login_date
0         1 2024-01-01
1         1 2024-01-02
2         2 2024-01-10
3         4 2024-01-17
4         4 2024-01-16
5         3 2024-01-10
6         2 2024-01-12
7         2 2024-01-13
8         1 2024-01-03
9         4 2024-01-18
10        1 2024-01-06
11        2 2024-01-11
12        3 2024-01-01
13        4 2024-01-15
14        1 2024-01-05
15        2 2024-01-11

In [9]:
df = user_logins[['user_id', 'login_date']].drop_duplicates()
df = df.sort_values(['user_id', 'login_date'])
df['rn'] = df.groupby('user_id').cumcount()
df['diff'] = df['login_date'] - pd.to_timedelta(df['rn'], unit='D')
streaks = df.groupby(['user_id', 'diff']).size().reset_index(name='count_streak')
streaks.groupby('user_id')['count_streak'].max().reset_index(name='max_streak_days')

   user_id  max_streak_days
0        1                3
1        2                4
2        3                1
3        4                4

14. Оконные функции (Тема: Сессионизация логов)
Это второй по популярности «всадник апокалипсиса» на технических интервью. Здесь проверяют умение комбинировать разные типы оконных функций друг за другом.

Контекст
Продуктовая команда хочет склеить сырые клики пользователя в сессии, чтобы посчитать, сколько раз за месяц человек целенаправленно заходил в сервис.

Таблица
web_logs:

user_id (int)

event_time (timestamp) — точное время клика.

Правило сессии
Сессия продолжается, пока перерыв между соседними кликами одного пользователя составляет не более 30 минут. Если пользователь не кликал ничего дольше 30 минут — следующий клик открывает новую сессию.

Твое задание
Для каждого пользователя посчитай общее количество его сессий за всё время.

Ожидаемый результат
Колонки: user_id, total_sessions.

In [2]:
import pandas as pd

# Таблица логов (строго по 16 элементов в каждом списке)
web_logs_data = {
    'user_id': [
        1, 1, 1, 1, 1,   # Юзер 1: Клики плотные, затем пауза 31 минута, затем снова клики. Итого: 2 сессии.
        2, 2, 2, 2,      # Юзер 2: Все клики с интервалом менее 30 минут. Итого: 1 сессия.
        3, 3, 3,         # Юзер 3: Редкие заходы, паузы по несколько часов. Итого: 3 сессии.
        4, 4, 4, 4       # Юзер 4: Сложный паттерн (граница ровно 30 минут и хаотичные клики). Итого: 2 сессии.
    ],
    'event_time': [
        # Юзер 1
        '2026-03-01 10:00:00', 
        '2026-03-01 10:15:00', # Пауза 15 мин (продолжение сессии 1)
        '2026-03-01 10:25:00', # Пауза 10 мин (продолжение сессии 1)
        '2026-03-01 10:56:00', # Пауза 31 минута -> НОВАЯ СЕССИЯ 2
        '2026-03-01 11:10:00', # Пауза 14 мин (продолжение сессии 2)
        
        # Юзер 2
        '2026-03-01 12:00:00', 
        '2026-03-01 12:29:59', # Пауза меньше 30 мин (продолжение сессии 1)
        '2026-03-01 12:45:00', # Пауза 15 мин (продолжение сессии 1)
        '2026-03-01 13:10:00', # Пауза 25 мин (продолжение сессии 1)
        
        # Юзер 3
        '2026-03-01 14:00:00', # СЕССИЯ 1
        '2026-03-01 15:00:00', # Пауза 60 мин -> СЕССИЯ 2
        '2026-03-01 18:30:00', # Пауза 3.5 часа -> СЕССИЯ 3
        
        # Юзер 4
        '2026-03-02 09:00:00', # СЕССИЯ 1
        '2026-03-02 09:30:00', # Пауза ровно 30 минут (по правилу это еще продолжение сессии 1)
        '2026-03-02 10:01:00', # Пауза 31 минута -> НОВАЯ СЕССИЯ 2
        '2026-03-02 10:05:00'  # Пауза 4 мин (продолжение сессии 2)
    ]
}

web_logs = pd.DataFrame(web_logs_data)
web_logs['event_time'] = pd.to_datetime(web_logs['event_time'])

# Перемешиваем логи, так как в реальности они пишутся параллельно от разных юзеров
web_logs = web_logs.sample(frac=1, random_state=42).reset_index(drop=True)

print("Таблица web_logs успешно создана!")
print(f"Всего сырых кликов в логе: {len(web_logs)}")

Таблица web_logs успешно создана!
Всего сырых кликов в логе: 16

In [3]:
query = """
with t as(
    select
        user_id,
        event_time,
        extract(epoch from (lead(event_time) over(partition by user_id order by event_time) - event_time)) / 60 as min_dif
    from web_logs
)
select 
    user_id,
    sum(case when min_dif > 30 or min_dif is null then 1 else 0 end) as total_sesions
from t
group by user_id
"""
result = duckdb.query(query).to_df()
result

   user_id  total_sesions
0        3            3.0
1        4            2.0
2        1            2.0
3        2            1.0

In [31]:
df = web_logs.sort_values(['user_id', 'event_time'], ascending=[True, True])
df['next_time'] = df.groupby('user_id')['event_time'].shift(-1)
df['dif'] = (df['next_time'] - df['event_time']).dt.total_seconds() / 60
df['dif'] = df['dif'].fillna(35)
df.groupby('user_id').agg(total_sessions = ('dif', lambda x:(x > 30).sum()))

         total_sessions
user_id
1                     2
2                     1
3                     3
4                     2

In [32]:
df_sorted = web_logs.sort_values(['user_id', 'event_time'])
dif_minutes = -df_sorted.groupby('user_id')['event_time'].diff(-1).dt.total_seconds() / 60
is_new_session = dif_minutes.fillna(35) > 30
result = (is_new_session.groupby(df_sorted['user_id'])
          .sum()
          .reset_index(name='total_sessions'))
result

   user_id  total_sessions
0        1               2
1        2               1
2        3               3
3        4               2

15. Финтех-платформа. Нам нужно для каждого пользователя рассчитать скользящий баланс за последние 3 дня, чтобы оценивать его платежеспособность в динамике.

Таблица
transactions:

user_id (int)

payment_date (date) — дата платежа.

amount (numeric) — сумма (может быть отрицательной для трат и положительной для пополнений).

Важно: У одного пользователя может быть несколько транзакций в один и тот же день.

Твое задание
Для каждой строки транзакции посчитай сумму всех транзакций этого пользователя за текущий день и 2 предыдущих дня.

Пример
Если у пользователя транзакции были 2026-05-10, 2026-05-11 и две транзакции 2026-05-12, то для транзакций от 12 числа в окно должны попасть вообще все эти строки (так как они укладываются в диапазон 3 дней).

Ожидаемый результат: все исходные колонки + колонка rolling_3d_sum.

In [4]:
import pandas as pd

# Таблица транзакций (строго по 15 элементов в каждом списке)
transactions_data = {
    'user_id': [
        1, 1, 1, 1, 1,    # Юзер 1: Несколько транзакций в один день + пропуски дат
        2, 2, 2, 2,       # Юзер 2: Плотные транзакции каждый день (с пополнениями и тратами)
        3, 3, 3, 3, 3, 3  # Юзер 3: Длинная история с большими временными разрывами
    ],
    'payment_date': [
        # Юзер 1
        '2026-05-10', 
        '2026-05-11', 
        '2026-05-12', '2026-05-12', # Две транзакции в один день (тест из примера)
        '2026-05-15',               # Окно сдвинулось, предыдущие дни уже не захватываются
        
        # Юзер 2
        '2026-05-01', '2026-05-02', '2026-05-03', '2026-05-04',
        
        # Юзер 3
        '2026-05-01', '2026-05-02', 
        '2026-05-10',                # Разрыв в 8 дней (баланс должен обнулиться и считаться заново)
        '2026-05-11', '2026-05-11', '2026-05-12'
    ],
    'amount': [
        # Юзер 1
        1000.00,  # 10 мая
        -300.00,  # 11 мая
        500.00,   -200.00,  # 12 мая (в окно на эту дату должны попасть все 4 строки: 10, 11, 12 мая)
        1500.00,  # 15 мая (в окне только этот день, так как 13 и 14 мая пусты)
        
        # Юзер 2
        5000.00, -1500.00, -2000.00, 3000.00,
        
        # Юзер 3
        400.00, 200.00, 
        10000.00, # 10 мая
        -5000.00, -1000.00, # 11 мая
        2000.00   # 12 мая
    ]
}

transactions = pd.DataFrame(transactions_data)
transactions['payment_date'] = pd.to_datetime(transactions['payment_date'])

# Перемешиваем транзакции, чтобы проверить устойчивость сортировки внутри оконной функции
transactions = transactions.sample(frac=1, random_state=42).reset_index(drop=True)

print("Таблица transactions успешно создана!")
print(f"Всего транзакций в базе: {len(transactions)}")

Таблица transactions успешно создана!
Всего транзакций в базе: 15

In [11]:
query = """
select 
    user_id,
    payment_date,
    amount,
    sum(amount) over(
        partition by user_id 
        order by payment_date 
        range between interval '2 days' preceding and current row
        ) as rolling_3d_sum
from transactions
"""
result = duckdb.query(query).to_df()
result

    user_id payment_date   amount  rolling_3d_sum
0         1   2026-05-10   1000.0          1000.0
1         1   2026-05-11   -300.0           700.0
2         1   2026-05-12    500.0          1000.0
3         1   2026-05-12   -200.0          1000.0
4         1   2026-05-15   1500.0          1500.0
5         3   2026-05-01    400.0           400.0
6         3   2026-05-02    200.0           600.0
7         3   2026-05-10  10000.0         10000.0
8         3   2026-05-11  -1000.0          4000.0
9         3   2026-05-11  -5000.0          4000.0
10        3   2026-05-12   2000.0          6000.0
11        2   2026-05-01   5000.0          5000.0
12        2   2026-05-02  -1500.0          3500.0
13        2   2026-05-03  -2000.0          1500.0
14        2   2026-05-04   3000.0          -500.0

In [37]:
transactions = transactions.sort_values(['user_id', 'payment_date']).groupby(['user_id', 'payment_date'])['amount'].sum().reset_index()
df_indexed = transactions.set_index('payment_date')
df_indexed['rolling_3d_sum'] = (
    df_indexed.groupby('user_id')['amount']
    .rolling(window='3D')
    .sum()
    .reset_index(level=0, drop=True) # убираем дублирующийся user_id из индекса после groupby
)
result = df_indexed.reset_index()
result

   payment_date  user_id   amount  rolling_3d_sum
0    2026-05-10        1   1000.0          1000.0
1    2026-05-11        1   -300.0           700.0
2    2026-05-12        1    300.0          1000.0
3    2026-05-15        1   1500.0          1500.0
4    2026-05-01        2   5000.0          5000.0
5    2026-05-02        2  -1500.0          3500.0
6    2026-05-03        2  -2000.0          1500.0
7    2026-05-04        2   3000.0          -500.0
8    2026-05-01        3    400.0           400.0
9    2026-05-02        3    200.0           600.0
10   2026-05-10        3  10000.0         10000.0
11   2026-05-11        3  -6000.0          4000.0
12   2026-05-12        3   2000.0          6000.0

16. Выведи список клиентов, у которых нет ни одного закрытого тикета (статус 'closed'), но при этом есть хотя бы один открытый (статус 'open').
Для каждого такого клиента выведи его имя и дату последнего открытого тикета.

Таблицы:

clients (client_id, name)

support_tickets (ticket_id, client_id, status, created_at)

In [2]:
import pandas as pd

# 1. Таблица клиентов (6 строк)
clients_data = {
    'client_id': [1, 2, 3, 4, 5, 6],
    'name': [
        'ООО Вектор',      # Только открытые тикеты (Целевой клиент)
        'ИП Петров',       # Есть и открытые, и закрытые (Должен отсеяться)
        'АО Спектр',       # Только закрытые тикеты (Должен отсеяться)
        'НКО Рассвет',     # Один открытый тикет (Целевой клиент)
        'ИП Сидоров',      # Вообще нет тикетов (Должен отсеяться)
        'ООО Трейд'        # Только открытые тикеты в один день (Целевой клиент)
    ]
}
clients = pd.DataFrame(clients_data)

# 2. Таблица тикетов техподдержки (11 строк во всех списках)
support_tickets_data = {
    'ticket_id': range(101, 112), # От 101 до 111 включительно
    'client_id': [
        1, 1,        # ООО Вектор: два открытых тикета
        2, 2, 2,     # ИП Петров: микс из открытых и закрытых
        3, 3,        # АО Спектр: все тикеты решены
        4,           # НКО Рассвет: один активный тикет
        6, 6, 6      # ООО Трейд: три открытых тикета
    ],
    'status': [
        'open', 'open',       # Юзер 1 (подходит)
        'open', 'closed', 'open', # Юзер 2 (есть closed, не подходит)
        'closed', 'closed',   # Юзер 3 (нет open, не подходит)
        'open',               # Юзер 4 (подходит)
        'open', 'open', 'open' # Юзер 6 (подходит)
    ],
    'created_at': [
        '2026-05-10 09:00:00', '2026-05-12 14:30:00', # Для Юзера 1 последняя дата: 12 мая
        '2026-05-11 10:00:00', '2026-05-14 11:15:00', '2026-05-15 16:00:00',
        '2026-05-01 13:00:00', '2026-05-05 09:45:00',
        '2026-05-20 17:00:00',                         # Для Юзера 4 последняя дата: 20 мая
        '2026-05-22 11:00:00', '2026-05-23 10:30:00', '2026-05-23 15:20:00' # Для Юзера 6 последняя дата: 23 мая 15:20
    ]
}
support_tickets = pd.DataFrame(support_tickets_data)
support_tickets['created_at'] = pd.to_datetime(support_tickets['created_at'])

# Перемешиваем тикеты, чтобы проверить корректность поиска максимальной даты (MAX/ROW_NUMBER)
support_tickets = support_tickets.sample(frac=1, random_state=42).reset_index(drop=True)

print("Таблицы clients и support_tickets успешно созданы!")
print(f"Всего клиентов: {len(clients)}, Всего тикетов: {len(support_tickets)}")

Таблицы clients и support_tickets успешно созданы!
Всего клиентов: 6, Всего тикетов: 11

In [3]:
query = """
SELECT 
    c.name,
    t_last.created_at
FROM clients c
-- Используем LATERAL, чтобы вытащить дату последнего открытого тикета
CROSS JOIN LATERAL (
    SELECT created_at
    FROM support_tickets st
    WHERE st.client_id = c.client_id 
      AND st.status = 'open'
    ORDER BY created_at DESC
    LIMIT 1
) t_last
-- Используем EXISTS, чтобы отфильтровать только тех, у кого НЕТ закрытых тикетов
WHERE NOT EXISTS (
    SELECT 1
    FROM support_tickets st_closed
    WHERE st_closed.client_id = c.client_id 
      AND st_closed.status = 'closed'
);
"""
result = duckdb.query(query).to_df()
result

          name          created_at
0   ООО Вектор 2026-05-12 14:30:00
1  НКО Рассвет 2026-05-20 17:00:00
2    ООО Трейд 2026-05-23 15:20:00

In [17]:
clients_with_closed = support_tickets[support_tickets['status'] == 'closed']['client_id'].unique()
df = support_tickets[~support_tickets['client_id'].isin(clients_with_closed)]
df = df.groupby('client_id', as_index=False).agg({'created_at': 'max'})
df.merge(clients)[['name', 'created_at']]

          name          created_at
0   ООО Вектор 2026-05-12 14:30:00
1  НКО Рассвет 2026-05-20 17:00:00
2    ООО Трейд 2026-05-23 15:20:00

17. «Агрессивные рекомендации»
Контекст:
У нас есть Пользователи (users), их Просмотренные товары (views) и Купленные товары (purchases).
Маркетологам нужно найти пользователей, которые смотрели товары, но не купили ничего из того, что смотрели, и при этом предложить им «рекомендацию» — самый дорогой товар из категории, которую они просматривали чаще всего.

Таблицы:

users (user_id)

views (view_id, user_id, product_id, category_id)

purchases (user_id, product_id)

products (product_id, category_id, price)

Твое задание:

Найди пользователей, у которых есть хотя бы один просмотр, но нет ни одной покупки в истории (EXISTS / NOT EXISTS).

Для каждого такого пользователя найди его «топовую категорию» (где было больше всего просмотров).

Из этой топовой категории выведи самый дорогой товар (CROSS JOIN LATERAL).

In [2]:
import pandas as pd

# 1. Справочник товаров (10 строк)
products_data = {
    'product_id': range(101, 111),
    'category_id': [1, 1, 1, 2, 2, 2, 3, 3, 4, 4], # Категории: 1, 2, 3, 4
    'price': [
        5000, 15000, 8000,     # Кат 1: Топ-товар 102 (15000)
        2500, 1200, 4000,      # Кат 2: Топ-товар 106 (4000)
        30000, 45000,          # Кат 3: Топ-товар 108 (45000)
        12000, 12000           # Кат 4: Два товара с одинаковой макс. ценой
    ]
}
products = pd.DataFrame(products_data)

# 2. Таблица пользователей (5 строк)
users = pd.DataFrame({'user_id': [1, 2, 3, 4, 5]})

# 3. Таблица просмотров (13 строк во всех списках)
views_data = {
    'view_id': range(1, 14),
    'user_id': [
        1, 1, 1, 1,  # Юзер 1: Просмотры Кат 1 (3 раза) и Кат 2 (1 раз). Покупок нет. Целевой!
        2, 2, 2,     # Юзер 2: Просмотры Кат 2 (2 раза) и Кат 3 (1 раз). Есть покупки. Отсеется!
        3, 3, 3,     # Юзер 3: Просмотры Кат 4 (3 раза, разные товары). Покупок нет. Целевой!
        4, 4,        # Юзер 4: Просмотры Кат 3 (2 раза). Покупок нет. Целевой!
        5            # Юзер 5: Просмотры Кат 1 (1 раз). Есть покупки другого товара. Отсеется!
    ],
    'product_id': [
        101, 101, 103, 104, # Юзер 1 (Товары из кат 1 и 2)
        104, 105, 107,      # Юзер 2
        109, 109, 110,      # Юзер 3 (Товары из кат 4)
        107, 108,           # Юзер 4
        101                 # Юзер 5
    ],
    'category_id': [
        1, 1, 1, 2,         # Юзер 1 чаше всего смотрел Кат 1
        2, 2, 3,            # Юзер 2 чаще всего смотрел Кат 2
        4, 4, 4,            # Юзер 3 чаще всего смотрел Кат 4
        3, 3,               # Юзер 4 чаще всего смотрел Кат 3
        1                   # Юзер 5
    ]
}
views = pd.DataFrame(views_data)

# 4. Таблица покупок (3 строки во всех списках)
purchases_data = {
    'user_id': [
        2,    # Юзер 2: Купил товар, который смотрел (104). Точно отсекается.
        5,    # Юзер 5: Купил товар 106, хотя смотрел только 101. Все равно отсекается (по условию "нет ни одной покупки в истории").
        2     # Доп. покупка Юзера 2
    ],
    'product_id': [104, 106, 105]
}
purchases = pd.DataFrame(purchases_data)

# Перемешиваем логи для симуляции реальной работы БД
views = views.sample(frac=1, random_state=42).reset_index(drop=True)

print("Все 4 таблицы успешно созданы и наполнены разнородными паттернами!")
print(f"Товаров: {len(products)}, Юзеров: {len(users)}, Просмотров: {len(views)}, Покупок: {len(purchases)}")

Все 4 таблицы успешно созданы и наполнены разнородными паттернами!
Товаров: 10, Юзеров: 5, Просмотров: 13, Покупок: 3

In [8]:
query = """
select
    v.user_id,
    category_id,
    count(v.view_id) as count_views
from views v
where not exists (
    select 1
    from purchases p
    where v.user_id = p.user_id
)
group by v.user_id, category_id
"""
result = duckdb.query(query).to_df()
result

   user_id  category_id  count_views
0        4            3            2
1        1            1            3
2        1            2            1
3        3            4            3

In [14]:
query = """
select 
    u.user_id,
    most_expensive_product.product_id as recommended_product
from users u
cross join lateral (
    select
        category_id
    from views v
    where u.user_id = v.user_id
    group by v.user_id, category_id
    order by count(v.view_id) desc
    limit 1
) most_popular_cat
cross join lateral (
select product_id
from products p
where p.category_id = most_popular_cat.category_id
order by price desc
limit 1
) most_expensive_product 
where not exists (
    select 1
    from purchases p
    where u.user_id = p.user_id
)
"""
result = duckdb.query(query).to_df()
result

   user_id  recommended_product
0        1                  102
1        3                  109
2        4                  108

In [22]:
df = views[~views['user_id'].isin(purchases.user_id)]
df = df.groupby(['user_id', 'category_id'], as_index=False).agg(count_views = ('view_id', 'count'))
df = df.sort_values(['user_id', 'count_views'], ascending=[True, False]).drop_duplicates(subset=['user_id'], keep='first')
df_pr = products[products['category_id'].isin(df.category_id)].sort_values(['category_id', 'price'], ascending=[True, False]).drop_duplicates(subset=['category_id'], keep='first')
df.merge(df_pr)[['user_id', 'product_id']]

   user_id  product_id
0        1         102
1        3         109
2        4         108

In [24]:
bought_users = set(purchases['user_id'])
non_buyers = views[~views['user_id'].isin(bought_users)]
category_counts = (
    non_buyers.groupby(['user_id', 'category_id'])
    .size()
    .reset_index(name='count_views')
)
top_categories = (
    category_counts.loc[category_counts.groupby('user_id')['count_views'].idxmax()]
)
top_products_in_cat = (
    products.loc[products.groupby('category_id')['price'].idxmax(), ['category_id', 'product_id']]
)
top_categories.merge(top_products_in_cat, on='category_id')[['user_id', 'product_id']]

   user_id  product_id
0        1         102
1        3         109
2        4         108

18. Анализ аномалий в поведении (Тема: Окна + Усеченное среднее)
На собеседованиях в крупные компании (вроде Авито или Яндекса) любят давать задачи, где нужно не просто применить оконку, а отсечь «шум» в данных перед расчетом метрики.

Контекст
Мы считаем среднее время между заказами пользователей, чтобы понять частоту удержания. Но у пользователей бывают аномалии: например, человек покупал каждую неделю, а потом уехал в отпуск на 3 месяца. Этот один огромный перерыв исказит наше среднее значение.

Таблица
orders:

user_id (int)

order_id (int)

created_at (timestamp) — время заказа.

Твое задание
Для каждого пользователя, который совершил три или более заказов, посчитай среднее время между его заказами.
Но с каверзой: для каждого пользователя нужно исключить один самый большой перерыв между заказами из расчета среднего.

Пример: Если у пользователя было 4 заказа и перерывы между ними составили 2 дня, 3 дня и 50 дней, то перерыв в 50 дней мы выбрасываем, и среднее считаем как (2 + 3) / 2 = 2.5 дня.

Ожидаемый результат
Колонки: user_id, trimmed_avg_gap (в формате interval или просто разница в днях/секундах — пиши как удобнее, главное логика).

In [3]:
import pandas as pd

# Таблица заказов (строго по 15 элементов в каждом списке)
orders_data = {
    'user_id': [
        1, 1, 1, 1,    # Юзер 1: 4 заказа (3 перерыва)
        2, 2, 2,       # Юзер 2: 3 заказа (2 перерыва)
        3, 3,          # Юзер 3: 2 заказа (1 перерыв -> должен отсеяться)
        4,             # Юзер 4: 1 заказ (0 перерывов -> должен отсеяться)
        5, 5, 5, 5, 5  # Юзер 5: 5 заказов (4 перерыва)
    ],
    'order_id': range(101, 116), # Генерирует 15 ID: от 101 до 115
    'created_at': [
        # Юзер 1
        '2026-01-01 10:00:00', '2026-01-03 10:00:00', '2026-01-06 10:00:00', '2026-02-25 10:00:00',
        
        # Юзер 2
        '2026-01-10 12:00:00', '2026-01-20 12:00:00', '2026-01-25 12:00:00',
        
        # Юзер 3
        '2026-02-01 15:00:00', '2026-02-05 15:00:00',
        
        # Юзер 4
        '2026-02-10 09:00:00',
        
        # Юзер 5
        '2026-03-01 00:00:00', '2026-03-02 00:00:00', '2026-03-03 00:00:00', '2026-03-04 00:00:00', '2026-03-05 00:00:00'
    ]
}

orders = pd.DataFrame(orders_data)
orders['created_at'] = pd.to_datetime(orders['created_at'])

# Перемешиваем строки, чтобы усложнить расчет интервалов через LAG/LEAD
orders = orders.sample(frac=1, random_state=42).reset_index(drop=True)

print("Таблица orders успешно создана!")
print(f"Всего строк в датафрейме: {len(orders)}")

Таблица orders успешно создана!
Всего строк в датафрейме: 15

In [43]:
query = """
with t_dif_time as(
    select 
        user_id,
        created_at - lag(created_at) over(partition by user_id order by created_at) as dif_time
    from orders
    where user_id in(
    select user_id from orders group by user_id having count(*) > 2
    )
),
t_rank as(
    select
        user_id,
        dif_time,
        rank() over(partition by user_id order by dif_time desc) as dif_rank
    from t_dif_time
    where dif_time is not null
),
t_union as(
    select user_id, dif_time
    from t_rank
    where user_id in (select user_id from t_rank group by user_id having count(distinct dif_rank) = 1)
    union all
    select user_id, dif_time
    from t_rank
    where dif_rank > 1
)
select
    user_id,
    avg(dif_time) as mean_time
from t_union
group by user_id
"""
result = duckdb.query(query).to_df()
result

   user_id       mean_time
0        2 5 days 00:00:00
1        1 2 days 12:00:00
2        5 1 days 00:00:00

In [8]:
# 0. Подготовка: приводим даты к формату datetime и сортируем
orders['created_at'] = pd.to_datetime(orders['created_at'])
orders = orders.sort_values(['user_id', 'created_at'])

# 1. Фильтруем пользователей: оставляем только тех, у кого строго больше 2 заказов
user_counts = orders['user_id'].value_counts()
valid_users = user_counts[user_counts > 2].index
df_filtered = orders[orders['user_id'].isin(valid_users)].copy()

# 2. Считаем интервалы времени (аналог LAG)
# Результат сохраняем в минутах или часах (для удобства агрегации)
df_filtered['dif_time'] = df_filtered.groupby('user_id')['created_at'].diff()

# Удаляем первую строку для каждого юзера, так как там будет NaN (аналог where dif_time is not null)
df_dif = df_filtered.dropna(subset=['dif_time']).copy()

# 3. Считаем ранг (аналог оконной функции RANK() OVER ... ORDER BY dif_time DESC)
# Используем метод 'min', как в SQL-функции rank()
df_dif['dif_rank'] = df_dif.groupby('user_id')['dif_time'].rank(method='min', ascending=False)

# 4. Логика фильтрации t_union:
# Нам нужно выбросить строки, где ранг равен 1 (самый большой перерыв), 
# НО ТОЛЬКО ЕСЛИ у пользователя количество уникальных рангов больше 1.
# Если у него все ранги равны 1 (все перерывы одинаковые), мы должны их ОСТАВИТЬ.

def filter_union(group):
    # Если все ранги одинаковые (число уникальных рангов == 1)
    if group['dif_rank'].nunique() == 1:
        return group # возвращаем группу целиком без изменений
    else:
        return group[group['dif_rank'] > 1] # выбрасываем самый большой перерыв (ранг 1)

# Применяем фильтр к каждому пользователю
df_union = df_dif.groupby('user_id', group_keys=False).apply(filter_union)

# 5. Финальная группировка и расчет среднего времени
# Переводим интервалы в удобный формат (например, в дни или часы) для расчета среднего
result = (df_union.groupby('user_id')['dif_time']
          .mean()
          .reset_index(name='mean_time'))

result

C:\Users\911\AppData\Local\Temp\ipykernel_13228\4181402649.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_union = df_dif.groupby('user_id', group_keys=False).apply(filter_union)

   user_id       mean_time
0        1 2 days 12:00:00
1        2 5 days 00:00:00
2        5 1 days 00:00:00

19. У нас есть таблица истории изменения статусов подписки пользователей. Нам нужно понять, насколько «нестабильны» наши клиенты.

Таблица
subscription_history:

user_id (int)

status (varchar) — статус подписки на определенный день (может принимать значения: 'active', 'paused', 'canceled').

updated_at (date) — дата фиксации статуса.

Примечание: Записи появляются только тогда, когда статус меняется, либо когда система обновляет лог. Но статус может повториться (например, сначала 'active', потом снова запись 'active', а потом 'paused').

Твое задание
Посчитай для каждого пользователя, сколько раз он целенаправленно переходил из статуса 'active' в статус 'paused'.

Пример: Если история юзера: active -> active -> paused -> active -> paused, то переходов было 2 (первые два active подряд — это не переход, а вот с active на paused — это переход).

Ожидаемый результат
Колонки: user_id, active_to_paused_count.

In [2]:
# Таблица истории подписок (строго по 14 элементов в каждом списке)
subscription_history_data = {
    'user_id': [
        1, 1, 1, 1, 1,  # Юзер 1: active -> active -> paused -> active -> paused. Итого: 2 перехода.
        2, 2, 2, 2,     # Юзер 2: active -> paused -> paused -> canceled. Итого: 1 переход.
        3, 3,           # Юзер 3: paused -> active. Переходов active->paused нет. Итого: 0.
        4, 4, 4         # Юзер 4: active -> canceled -> paused. Прямого перехода нет. Итого: 0.
    ],
    'status': [
        # Юзер 1 (Пример из условия)
        'active', 'active', 'paused', 'active', 'paused',
        
        # Юзер 2 (Повтор целевого статуса)
        'active', 'paused', 'paused', 'canceled',
        
        # Юзер 3 (Обратный порядок)
        'paused', 'active',
        
        # Юзер 4 (Переход через посредника)
        'active', 'canceled', 'paused'
    ],
    'updated_at': [
        # Юзер 1
        '2026-01-01', '2026-01-05', '2026-01-10', '2026-01-15', '2026-01-20',
        
        # Юзер 2
        '2026-02-01', '2026-02-02', '2026-02-10', '2026-02-15',
        
        # Юзер 3
        '2026-03-01', '2026-03-05',
        
        # Юзер 4
        '2026-04-01', '2026-04-02', '2026-04-05'
    ]
}

subscription_history = pd.DataFrame(subscription_history_data)
subscription_history['updated_at'] = pd.to_datetime(subscription_history['updated_at'])

# Перемешиваем строки, чтобы усложнить задачу для оконной функции LAG
subscription_history = subscription_history.sample(frac=1, random_state=42).reset_index(drop=True)

print("Таблица subscription_history успешно создана!")
print(f"Всего строк в логе изменений: {len(subscription_history)}")

Таблица subscription_history успешно создана!
Всего строк в логе изменений: 14

In [5]:
query = """
with t_next as(
select 
    user_id,
    status,
    lead(status) over(partition by user_id order by updated_at) as next_st
from subscription_history
)
select 
    user_id,
    sum(case when status = 'active' and next_st = 'paused' then 1 else 0 end) as active_to_paused_count
from t_next
group by user_id
"""
result = duckdb.query(query).to_df()
result

   user_id  active_to_paused_count
0        2                     1.0
1        3                     0.0
2        4                     0.0
3        1                     2.0

In [ ]:
df = subscription_history.sort_values(['user_id', 'updated_at'])
df['next_st'] = df.groupby('user_id')['status'].shift(-1)
is_transition = (df['status'] == 'active') & (df['next_st'] == 'paused')
df['transition_flag'] = is_transition.astype(int)
df.groupby('user_id', as_index=False).agg(active_to_paused_count = ('transition_flag', 'sum'))

   user_id  active_to_paused_count
0        1                       2
1        2                       1
2        3                       0
3        4                       0

20. В e-commerce важно следить за ценообразованием. Нам нужно понять, насколько цена конкретного товара отличается от цен других товаров в этой же категории.

Таблица
products:

product_id (int)

category_id (int)

price (numeric)

Твое задание
Для каждого товара выведи его product_id, category_id, price, а также среднюю цену ВСЕХ ОСТАЛЬНЫХ товаров в этой категории (то есть текущий товар при расчете средней цены категории учитываться не должен).

In [12]:
import pandas as pd

# Таблица товаров (строго по 10 элементов в каждом списке)
products_data = {
    'product_id': range(101, 111), # От 101 до 110 включительно
    'category_id': [
        1, 1, 1, 1,  # Категория 1 (4 товара)
        2, 2, 2,     # Категория 2 (3 товара)
        3, 3,        # Категория 3 (2 товара - экстремальный тест)
        4            # Категория 4 (1 товар - экстремальный тест)
    ],
    'price': [
        # Категория 1
        1000.00, 2000.00, 3000.00, 4000.00,
        
        # Категория 2
        5000.00, 5000.00, 8000.00,
        
        # Категория 3
        1500.00, 2500.00,
        
        # Категория 4
        10000.00
    ]
}

products = pd.DataFrame(products_data)

# Перемешиваем строки для симуляции реального хаотичного наполнения БД
products = products.sample(frac=1, random_state=42).reset_index(drop=True)

print("Таблица products успешно создана!")
print(f"Всего товаров в каталоге: {len(products)}")

Таблица products успешно создана!
Всего товаров в каталоге: 10

In [29]:
query = """
select
    product_id,
    category_id,
    price,
    coalesce(
        round(
            (sum(price) over(partition by category_id) - price) / 
            nullif(count(price) over(partition by category_id) - 1, 0
            ),1
        ),
    0) as other_products_avg_price
from products
"""
result = duckdb.query(query).to_df()
result

   product_id  category_id    price  other_products_avg_price
0         102            1   2000.0                    2666.7
1         101            1   1000.0                    3000.0
2         103            1   3000.0                    2333.3
3         104            1   4000.0                    2000.0
4         109            3   2500.0                    1500.0
5         108            3   1500.0                    2500.0
6         110            4  10000.0                       0.0
7         106            2   5000.0                    6500.0
8         105            2   5000.0                    6500.0
9         107            2   8000.0                    5000.0

In [31]:
agg_category = products.groupby('category_id', as_index=False).agg(sum_price = ('price', 'sum'), count_products = ('product_id', 'count'))
df = products.merge(agg_category)
df['other_products_avg_price'] = (((df['sum_price'] - df['price']) / (df['count_products'] - 1)).fillna(0)).round(1)
df[['product_id', 'category_id', 'price', 'other_products_avg_price']]

   product_id  category_id    price  other_products_avg_price
0         109            3   2500.0                    1500.0
1         102            1   2000.0                    2666.7
2         106            2   5000.0                    6500.0
3         101            1   1000.0                    3000.0
4         108            3   1500.0                    2500.0
5         103            1   3000.0                    2333.3
6         110            4  10000.0                       0.0
7         105            2   5000.0                    6500.0
8         104            1   4000.0                    2000.0
9         107            2   8000.0                    5000.0

In [33]:
sum_price = products.groupby('category_id')['price'].transform('sum')
count_products = products.groupby('category_id')['product_id'].transform('count')
products['other_products_avg_price'] = (
    ((sum_price - products['price']) / (count_products - 1))
    .fillna(0)
    .round(1)
)
products

   product_id  category_id    price  other_products_avg_price
0         109            3   2500.0                    1500.0
1         102            1   2000.0                    2666.7
2         106            2   5000.0                    6500.0
3         101            1   1000.0                    3000.0
4         108            3   1500.0                    2500.0
5         103            1   3000.0                    2333.3
6         110            4  10000.0                       0.0
7         105            2   5000.0                    6500.0
8         104            1   4000.0                    2000.0
9         107            2   8000.0                    5000.0

21. Нам нужно проанализировать поведение новых пользователей в первые сутки после их первого захода.

Таблицы
users (user_id, registered_at)

sessions (session_id, user_id, source, created_at)

orders (order_id, user_id, amount, created_at)

refunds (order_id, created_at) — таблица возвратов. Если заказ есть здесь, значит, по нему оформили возврат.

Твое задание
Для каждого пользователя найди его самую первую сессию в системе.
Затем найди его самый первый заказ, который был совершен в течение 24 часов ПОСЛЕ этой первой сессии.

Условия фильтрации:

В финальную выборку должны попасть только те пользователи, у которых этот первый заказ не был возвращен (его не должно быть в таблице refunds).

Пользователи, у которых нет сессий или нет заказа в первые 24 часа после сессии, должны отвалиться (их выводим через CROSS JOIN LATERAL).

Ожидаемый результат
Колонки: user_id, first_session_source (источник первой сессии), first_order_id, amount.

In [1]:
import pandas as pd

# 1. Таблица пользователей (5 строк)
users_data = {
    'user_id': [1, 2, 3, 4, 5],
    'registered_at': [
        '2026-05-01 10:00:00',
        '2026-05-02 11:00:00',
        '2026-05-03 12:00:00',
        '2026-05-04 13:00:00',
        '2026-05-05 14:00:00'
    ]
}
users = pd.DataFrame(users_data)
users['registered_at'] = pd.to_datetime(users['registered_at'])

# 2. Таблица сессий (ровно по 8 элементов в каждом списке)
sessions_data = {
    'session_id': range(101, 109), # Генерирует 8 ID: от 101 до 108
    'user_id': [
        1, 1,  # Юзер 1: первая сессия с google
        2, 2,  # Юзер 2: первая сессия с facebook
        3,     # Юзер 3: первая сессия с organic
        4,     # Юзер 4: первая сессия с yandex
        5, 5   # Юзер 5: первая сессия с vk
    ],
    'source': [
        'google', 'email', 
        'facebook', 'google', 
        'organic', 
        'yandex', 
        'vk', 'telegram'
    ],
    'created_at': [
        '2026-05-01 10:05:00', '2026-05-01 15:00:00',
        '2026-05-02 11:10:00', '2026-05-02 18:00:00',
        '2026-05-03 12:15:00',
        '2026-05-04 13:05:00',
        '2026-05-05 14:30:00', '2026-05-06 09:00:00'
    ]
}
sessions = pd.DataFrame(sessions_data)
sessions['created_at'] = pd.to_datetime(sessions['created_at'])

# 3. Таблица заказов (ровно по 6 элементов в каждом списке)
orders_data = {
    'order_id': range(1001, 1007), # Генерирует 6 ID: от 1001 до 1006
    'user_id': [
        1, 1,  # Юзер 1: заказ в первые сутки (входит) и повторный заказ
        2,     # Юзер 2: заказ в первые сутки, но по нему будет ВОЗВРАТ (отсеется)
        3,     # Юзер 3: заказ оформлен через 26 часов после сессии (отсеется)
        4,     # Юзер 4: заказ в первые сутки (входит)
        5      # Юзер 5: заказ в первые сутки, но по нему будет ВОЗВРАТ (отсеется)
    ],
    'amount': [1500.00, 3000.00, 2500.00, 4200.00, 850.00, 1900.00],
    'created_at': [
        '2026-05-01 14:20:00', '2026-05-03 11:00:00',
        '2026-05-02 16:40:00',
        '2026-05-04 14:30:00',
        '2026-05-04 20:15:00',
        '2026-05-06 10:00:00'
    ]
}
orders = pd.DataFrame(orders_data)
orders['created_at'] = pd.to_datetime(orders['created_at'])

# 4. Таблица возвратов (ровно по 2 элемента в каждом списке)
refunds_data = {
    'order_id': [1003, 1006], # Возвраты по заказам Юзера 2 и Юзера 5
    'created_at': ['2026-05-03 09:00:00', '2026-05-07 11:30:00']
}
refunds = pd.DataFrame(refunds_data)
refunds['created_at'] = pd.to_datetime(refunds['created_at'])

# Перемешиваем таблицы для симуляции реального лога
sessions = sessions.sample(frac=1, random_state=42).reset_index(drop=True)
orders = orders.sample(frac=1, random_state=42).reset_index(drop=True)

print("Все датафреймы успешно созданы и проверены!")
print(f"Пользователи: {len(users)}, Сессии: {len(sessions)}, Заказы: {len(orders)}, Возвраты: {len(refunds)}")

Все датафреймы успешно созданы и проверены!
Пользователи: 5, Сессии: 8, Заказы: 6, Возвраты: 2

In [4]:
query = """
select
    u.user_id,
    t_first_session.source as first_session_source,
    t_first_order.order_id as first_order_id
from users u cross join lateral(
    select 
        source,
        created_at
    from sessions s
    where u.user_id = s.user_id
    order by s.created_at
    limit 1
) t_first_session
cross join lateral(
    select order_id
    from orders o
    where u.user_id = o.user_id
        and o.created_at between t_first_session.created_at and t_first_session.created_at + interval '1 day'
    order by o.created_at
    limit 1
) t_first_order
where not exists(
    select 1
    from refunds r
    where r.order_id = t_first_order.order_id
)
"""
result = duckdb.query(query).to_df()
result

   user_id first_session_source  first_order_id
0        1               google            1001
1        4               yandex            1005

In [12]:
first_sessions = (sessions.sort_values(['user_id', 'created_at'])
                  .drop_duplicates(subset=['user_id'], keep='first')
                  [['user_id', 'source', 'created_at']])
first_sessions.rename(columns={'created_at': 'session_time'}, inplace=True)
refunds_orders = set(refunds['order_id'])
first_orders = (orders.sort_values(['user_id', 'created_at'])
                .drop_duplicates(subset=['user_id'], keep='first')
                [['user_id', 'order_id', 'created_at']])
first_orders.rename(columns={'created_at': 'order_time', 'order_id': 'first_order_id'}, inplace=True)
non_refunds = first_orders[~first_orders['first_order_id'].isin(refunds_orders)]
df = first_sessions.merge(non_refunds, on='user_id', how='inner')
mask = (df['order_time'] >= df['session_time']) & (df['order_time'] <= df['session_time'] + pd.Timedelta(days=1))
df_filtered = df[mask]
result = df_filtered.rename(columns={'source': 'first_session_source'})[
    ['user_id', 'first_session_source', 'first_order_id']
]
result

   user_id first_session_source  first_order_id
0        1               google            1001
2        4               yandex            1005

22. Кросс-табличный продуктовый воронкообразный анализ с налогами и скидками
Контекст
Маркетологи запустили несколько рекламных каналов. Нам нужно посчитать чистую выручку (Net Revenue) по разным маркетинговым каналам и типам устройств, но только для определенной когорты пользователей и с учетом специфики налогов разных стран.

Таблицы в базе (4 штуки)
users (Пользователи)

user_id (int)

country (varchar) — страна пользователя (например, 'USA', 'DE', 'FR')

registered_at (timestamp) — дата и время регистрации

sessions (Рекламные сессии)

session_id (int)

user_id (int)

utm_channel (varchar) — рекламный канал (например, 'google', 'facebook', 'organic')

device (varchar) — девайс ('desktop', 'mobile')

created_at (timestamp) — время старта сессии

orders (Заказы)

order_id (int)

user_id (int)

session_id (int) — сессия, в рамках которой был сделан заказ (может быть NULL, если заказ сделан без сессии напрямую)

gross_amount (numeric) — «грязная» стоимость заказа до скидок и налогов

created_at (timestamp)

discounts (Скидки)

order_id (int) — если заказа нет в этой таблице, значит, скидки не было

discount_amount (numeric) — сумма скидки

country_taxes (Справочник налогов)

country (varchar) — страна

tax_rate (numeric) — налоговая ставка (например, 0.20 означает налог 20%)

Твое задание
Посчитай суммарную чистую выручку (Net Revenue), сгруппированную по utm_channel (маркетинговый канал) и device (тип устройства).

Хитрые условия (Внимательно читай каждое):
Расчет чистой выручки: Формула для одного заказа: (gross_amount - discount_amount) * (1 - tax_rate). Если скидки не было, вычитать нужно 0.

Фильтр по сессиям: Нас интересуют только те заказы, которые привязаны к конкретной сессии (то есть orders.session_id не должен быть пустым).

Ограничение по окну конверсии: Мы берем в расчет только те заказы, которые были совершены в течение первых 7 дней (ровно 168 часов) с момента регистрации пользователя. Все заказы, сделанные позже 7-го дня жизни юзера, должны быть проигнорированы.

Когортный фильтр: В итоговый расчет должны попасть только те пользователи, которые вообще совершили свой самый первый заказ на платформе с мобильного устройства (device = 'mobile'). Если первый заказ юзера был с десктопа — этого юзера и ВСЕ его заказы нужно полностью исключить из отчета.

Ожидаемый результат
Колонки: utm_channel, device, total_net_revenue.
Сортировка: по убыванию выручки.

In [2]:
import pandas as pd

# 1. Справочник налогов (3 строки)
taxes_data = {
    'country': ['USA', 'DE', 'FR'],
    'tax_rate': [0.08, 0.19, 0.20] # США — 8%, Германия — 19%, Франция — 20%
}
country_taxes = pd.DataFrame(taxes_data)

# 2. Таблица пользователей (5 строк)
users_data = {
    'user_id': [1, 2, 3, 4, 5],
    'country': ['USA', 'DE', 'FR', 'USA', 'DE'],
    'registered_at': [
        '2026-05-01 10:00:00',
        '2026-05-01 12:00:00',
        '2026-05-02 09:00:00',
        '2026-05-03 15:00:00',
        '2026-05-04 11:00:00'
    ]
}
users = pd.DataFrame(users_data)
users['registered_at'] = pd.to_datetime(users['registered_at'])

# 3. Таблица сессий (7 строк во всех списках)
sessions_data = {
    'session_id': [101, 102, 103, 104, 105, 106, 107],
    'user_id': [1, 1, 2, 3, 4, 4, 5],
    'utm_channel': ['google', 'facebook', 'google', 'organic', 'facebook', 'google', 'organic'],
    'device': ['mobile', 'desktop', 'desktop', 'mobile', 'mobile', 'desktop', 'mobile'],
    'created_at': [
        '2026-05-01 10:05:00', '2026-05-03 14:00:00',
        '2026-05-01 12:30:00',
        '2026-05-02 09:15:00',
        '2026-05-03 16:00:00', '2026-05-15 11:00:00',
        '2026-05-04 11:30:00'
    ]
}
sessions = pd.DataFrame(sessions_data)
sessions['created_at'] = pd.to_datetime(sessions['created_at'])

# 4. Таблица заказов (7 строк во всех списках)
orders_data = {
    'order_id': [1001, 1002, 1003, 1004, 1005, 1006, 1007],
    'user_id': [1, 1, 2, 3, 4, 4, 5],
    'session_id': [101, 102, 103, 104, 105, 106, None], # Заказ 1007 без сессии (должен отвалиться)
    'gross_amount': [100.0, 150.0, 200.0, 50.0, 300.0, 500.0, 80.0],
    'created_at': [
        '2026-05-01 10:20:00', # Юзер 1: 1-й заказ с mobile (Входит в когорту)
        '2026-05-03 14:30:00', # Юзер 1: 2-й заказ с desktop (Тоже учитывается, так как сам юзер целевой)
        '2026-05-01 13:00:00', # Юзер 2: 1-й заказ с desktop (ВСЕ заказы этого юзера отсекаются)
        '2026-05-02 09:45:00', # Юзер 3: 1-й заказ с mobile (Входит в когорту)
        '2026-05-03 16:30:00', # Юзер 4: 1-й заказ с mobile (Входит в когорту)
        '2026-05-15 11:30:00', # Юзер 4: 2-й заказ сделан на 12-й день (> 7 дней, должен отсеяться)
        '2026-05-04 12:00:00'  # Юзер 5: 1-й заказ без сессии (отвалится по фильтру сессий)
    ]
}
orders = pd.DataFrame(orders_data)
orders['created_at'] = pd.to_datetime(orders['created_at'])

# 5. Таблица скидок (3 строки во всех списках)
discounts_data = {
    'order_id': [1001, 1003, 1005],
    'discount_amount': [10.0, 20.0, 50.0] # Для остальных заказов скидка должна быть 0
}
discounts = pd.DataFrame(discounts_data)

# Перемешиваем логи для симуляции реального хаоса в СУБД
sessions = sessions.sample(frac=1, random_state=42).reset_index(drop=True)
orders = orders.sample(frac=1, random_state=42).reset_index(drop=True)

print("Все кросс-табличные датафреймы успешно созданы!")
print(f"Юзеров: {len(users)}, Сессий: {len(sessions)}, Заказов: {len(orders)}, Скидок: {len(discounts)}")

Все кросс-табличные датафреймы успешно созданы!
Юзеров: 5, Сессий: 7, Заказов: 7, Скидок: 3

In [16]:
query = """
select
    s.utm_channel,
    s.device,
    sum((o.gross_amount - coalesce(d.discount_amount, 0)) * (1 - coalesce(c.tax_rate, 0))) as total_net_revenue
from users u 
    join orders o
        on u.user_id = o.user_id
        and o.created_at between u.registered_at and u.registered_at + interval '7 day'
    join sessions s
        on o.session_id = s.session_id
    left join discounts d
        on o.order_id = d.order_id
    join country_taxes c
        on u.country = c.country
where u.user_id in(
select
    u.user_id
from users u
    cross join lateral(
        select session_id
        from orders o
        where u.user_id = o.user_id
        order by created_at
        limit 1
    ) first_order
    cross join lateral(
    select device
    from sessions s
    where 
        first_order.session_id = s.session_id
        and device = 'mobile'
    )
)
group by 
    s.utm_channel,
    s.device
"""
result = duckdb.query(query).to_df()
result

  utm_channel   device  total_net_revenue
0    facebook   mobile              230.0
1    facebook  desktop              138.0
2      google   mobile               82.8
3     organic   mobile               40.0

In [ ]:
query = """
WITH user_first_device AS (
    SELECT DISTINCT ON (o.user_id)
        o.user_id,
        s.device AS first_order_device
    FROM orders o
    LEFT JOIN sessions s ON o.session_id = s.session_id
    ORDER BY o.user_id, o.created_at ASC
)
SELECT
    s.utm_channel,
    s.device,
    SUM((o.gross_amount - COALESCE(d.discount_amount, 0)) * (1 - COALESCE(c.tax_rate, 0))) AS total_net_revenue
FROM users u 
JOIN user_first_device fd 
    ON u.user_id = fd.user_id AND fd.first_order_device = 'mobile'
JOIN orders o 
    ON u.user_id = o.user_id
    AND o.session_id IS NOT NULL -- Фильтр: заказ должен быть из сессии
    AND o.created_at BETWEEN u.registered_at AND u.registered_at + INTERVAL '7 days'
JOIN sessions s 
    ON o.session_id = s.session_id
LEFT JOIN discounts d 
    ON o.order_id = d.order_id
LEFT JOIN country_taxes c 
    ON u.country = c.country
GROUP BY 
    s.utm_channel,
    s.device
ORDER BY 
    total_net_revenue DESC;
"""
result = duckdb.query(query).to_df()
result

  utm_channel   device  total_net_revenue
0    facebook   mobile              230.0
1    facebook  desktop              138.0
2      google   mobile               82.8
3     organic   mobile               40.0

In [38]:
first_orders = orders.sort_values(['user_id', 'created_at']).drop_duplicates(subset=['user_id'], keep='first')
mobile_users = set(first_orders.merge(sessions[sessions['device'] == 'mobile'], on='session_id')['user_id_x'])
df_uo = users[users['user_id'].isin(mobile_users)].merge(orders[~orders['session_id'].isna()])
df_uos = df_uo[(df_uo['created_at'] >= df_uo['registered_at']) & (df_uo['created_at'] <= df_uo['registered_at'] + pd.Timedelta(days=7))].merge(sessions, on='session_id')[['country', 'gross_amount', 'utm_channel', 'device', 'order_id']]
df_uosdc = df_uos.merge(discounts, how='left').merge(country_taxes, how='left')[['utm_channel', 'device', 'gross_amount', 'discount_amount', 'tax_rate']]
df_uosdc['discount_amount'] = df_uosdc['discount_amount'].fillna(0)
df_uosdc['tax_rate'] = df_uosdc['tax_rate'].fillna(0)
df_uosdc['net_revenue'] = (df_uosdc['gross_amount'] - df_uosdc['discount_amount']) * (1 - df_uosdc['tax_rate'])
df_uosdc.groupby(['utm_channel', 'device'], as_index=False).agg(total_net_revenue=('net_revenue', 'sum')).sort_values('total_net_revenue', ascending=False)

  utm_channel   device  total_net_revenue
1    facebook   mobile              230.0
0    facebook  desktop              138.0
2      google   mobile               82.8
3     organic   mobile               40.0

In [44]:
first_orders = orders.sort_values(['user_id', 'created_at']).drop_duplicates(subset=['user_id'], keep='first')
mobile_sessions = set(sessions.loc[sessions['device'] == 'mobile', 'session_id'])
mobile_users = set(first_orders[first_orders['session_id'].isin(mobile_sessions)]['user_id'])
valid_orders = orders.dropna(subset=['session_id'])[['order_id', 'user_id', 'session_id', 'created_at', 'gross_amount']]
filtered_users = users[users['user_id'].isin(mobile_users)][['user_id', 'registered_at', 'country']]
df_uo = valid_orders.merge(filtered_users, on='user_id', how='inner')
mask_7d = (df_uo['created_at'] >= df_uo['registered_at']) & (df_uo['created_at'] <= df_uo['registered_at'] + pd.Timedelta(days=7))
df_uo_filtered = df_uo[mask_7d]
df_final = (
    df_uo_filtered[['order_id', 'session_id', 'gross_amount', 'country']]
    .merge(sessions[['session_id', 'utm_channel', 'device']], on='session_id', how='inner')
    .merge(discounts[['order_id', 'discount_amount']], on='order_id', how='left')
    .merge(country_taxes[['country', 'tax_rate']], on='country', how='left')
)
net_revenue = (
    (df_final['gross_amount'] - df_final['discount_amount'].fillna(0)) 
    * (1 - df_final['tax_rate'].fillna(0))
)
result = (
    net_revenue.groupby([df_final['utm_channel'], df_final['device']])
    .sum()
    .reset_index(name='total_net_revenue')
    .sort_values('total_net_revenue', ascending=False)
)
result

  utm_channel   device  total_net_revenue
1    facebook   mobile              230.0
0    facebook  desktop              138.0
2      google   mobile               82.8
3     organic   mobile               40.0

23. Таблица reports_stg.watch_content (таблица с просмотрами видео), поля:
- user_id - идентификатор пользователя
- video_id - идентификатор просмотренного видео
- date - дата просмотра видео  
Примечание: 1 строка в таблице - 1 просмотр видео  
ЗАДАЧА: Вывести список пользователей, смотревших video_id 1 и 3 (посмотрел и видео 1, и видео 3), но не смотревших 2

In [5]:
import pandas as pd

# Данные для таблицы просмотров (14 строк во всех списках)
watch_content_data = {
    'user_id': [
        101, 101,       # Юзер 101: Посмотрел 1 и 3. Покупок/просмотров видео 2 нет. ИДЕАЛЬНЫЙ ЦЕЛЕВОЙ!
        102, 102, 102,  # Юзер 102: Посмотрел 1, 3 и запрещенное видео 2. ДОЛЖЕН ОТСЕЯТЬСЯ.
        103,            # Юзер 103: Посмотрел только 1. Должен отсеяться.
        104,            # Юзер 104: Посмотрел только 3. Должен отсеяться.
        105,            # Юзер 105: Посмотрел только 2. Должен отсеяться.
        106, 106, 106,  # Юзер 106: Посмотрел 1 и 3 несколько раз (дубли). Видео 2 не смотрел. ЦЕЛЕВОЙ!
        101, 102        # Дополнительные просмотры для разнообразия
    ],
    'video_id': [
        1, 3,
        1, 2, 3,
        1,
        3,
        2,
        1, 1, 3,
        3, 1
    ],
    'date': [
        '2026-06-01', '2026-06-02',
        '2026-06-01', '2026-06-02', '2026-06-03',
        '2026-06-02',
        '2026-06-03',
        '2026-06-04',
        '2026-06-01', '2026-06-02', '2026-06-03',
        '2026-06-04', '2026-06-05'
    ]
}

watch_content = pd.DataFrame(watch_content_data)
watch_content['date'] = pd.to_datetime(watch_content['date'])

# Перемешиваем строки для симуляции реального лога просмотров
watch_content = watch_content.sample(frac=1, random_state=42).reset_index(drop=True)

print("Таблица reports_stg.watch_content успешно создана!")
print(f"Всего строк с просмотрами: {len(watch_content)}")

Таблица reports_stg.watch_content успешно создана!
Всего строк с просмотрами: 13

In [3]:
query = """
select user_id
from stg.watch_content
where 
    video_id = 1
    or video_id = 2
    or video_id = 3
group by user_id
having
    count(distinct case when video_id = 1 then video_id end) > 0
    and count(distinct case when video_id = 3 then video_id end) > 0
    and count(distinct case when video_id = 2 then video_id end) = 0
"""
result = duckdb.query(query).to_df()
result

   user_id
0      106
1      101

In [39]:
watch_content[(watch_content['video_id'] == 1)|(watch_content['video_id'] == 3)]

    user_id  video_id       date
0       101         3 2026-06-04
1       106         1 2026-06-02
2       101         1 2026-06-01
3       106         1 2026-06-01
4       103         1 2026-06-02
5       102         1 2026-06-01
6       101         3 2026-06-02
7       102         1 2026-06-05
8       102         3 2026-06-03
10      106         3 2026-06-03
12      104         3 2026-06-03

In [16]:
vid_1 = watch_content[watch_content['video_id'] == 1]
vid_3 = watch_content[watch_content['video_id'] == 3]['user_id']
vid_2 = watch_content[watch_content['video_id'] == 2]['user_id']
vid_1_3 = vid_1[vid_1['user_id'].isin(vid_3)]
vid_1_3[~vid_1_3['user_id'].isin(vid_2)].drop_duplicates(subset=['user_id'], keep='first')[['user_id']]

   user_id
1      106
2      101

In [17]:
filtered_df = watch_content[watch_content['video_id'].isin([1, 2, 3])]
filtered_df.groupby('user_id')\
.filter(lambda x: 1 in x['video_id'].values 
                and 3 in x['video_id'].values 
                and 2 not in x['video_id'].values)\
.drop_duplicates(subset=['user_id'])[['user_id']]

   user_id
0      101
1      106

In [18]:
users_1 = set(watch_content.loc[watch_content['video_id'] == 1, 'user_id'])
users_3 = set(watch_content.loc[watch_content['video_id'] == 3, 'user_id'])
users_2 = set(watch_content.loc[watch_content['video_id'] == 2, 'user_id'])
target_users = (users_1 & users_3) - users_2
pd.DataFrame({'user_id': list(target_users)})

   user_id
0      106
1      101

24. Таблица raw.orders (таблица с покупками товаров по датам):   
- user_id - идентификатор пользователя
- transaction_datetime - дата и время покупки (для одного пользователя не может быть два заказа в одно и тоже время)
- item_id - id товара
- order_id - id покупки     
Таблица dicts.items (словарь соответствия id товара и наименование бренда, наименования товара):
- item_id     
- brand     
- name                  
- price   
Для каждого пользователя вывести наименование и цену самого дорогого товара в его первой транзакции.   
Поля в аутпут-таблице:
- user_id
- name
- price

In [2]:
import pandas as pd

# 1. Справочник товаров (6 строк)
items_data = {
    'item_id': range(501, 507),
    'brand': ['Apple', 'Samsung', 'Xiaomi', 'Sony', 'JBL', 'Apple'],
    'name': ['iPhone 15', 'Galaxy S24', 'Redmi Note 13', 'PlayStation 5', 'Flip 6', 'iPad Air'],
    'price': [90000.00, 85000.00, 25000.00, 50000.00, 10000.00, 70000.00]
}
items = pd.DataFrame(items_data)

# 2. Таблица покупок (10 строк во всех списках)
orders_data = {
    'user_id': [
        101, 101, 101, # Юзер 101: Первая транзакция в 10:00 (два товара: за 90к и 70к). Должен выбраться iPhone за 90к.
        102, 102,      # Юзер 102: Первая транзакция в 11:00 (один товар за 25к). Вторая транзакция дороже, но она должна игнорироваться.
        103, 103, 103, # Юзер 103: Первая транзакция в 12:00 (два товара с одинаковой ценой для теста дублей).
        101, 102       # Дополнительные покупки для разнообразия
    ],
    'transaction_datetime': [
        # Юзер 101
        '2026-06-01 10:00:00', '2026-06-01 10:00:00', '2026-06-01 15:30:00',
        # Юзер 102
        '2026-06-01 11:00:00', '2026-06-02 14:00:00',
        # Юзер 103
        '2026-06-02 12:00:00', '2026-06-02 12:00:00', '2026-06-02 12:00:00',
        # Допы
        '2026-06-03 18:00:00', '2026-06-04 09:15:00'
    ],
    'item_id': [
        501, 506, 504, # Юзер 101 (в первой транзакции iPhone 90к и iPad 70к)
        503, 501,      # Юзер 102 (первая покупка — Redmi 25к, вторая — iPhone 90к)
        505, 505, 503, # Юзер 103 (в первой транзакции две колонки по 10к и один Redmi за 25к)
        502, 502
    ],
    'order_id': [
        10001, 10001, 10002,
        10003, 10004,
        10005, 10005, 10005,
        10006, 10007
    ]
}

orders = pd.DataFrame(orders_data)
orders['transaction_datetime'] = pd.to_datetime(orders['transaction_datetime'])

# Перемешиваем строки, так как СУБД возвращает данные не отсортированными
orders = orders.sample(frac=1, random_state=42).reset_index(drop=True)

print("Таблицы raw.orders и dicts.items успешно созданы!")
print(f"Строк в заказах: {len(orders)}, Строк в товарах: {len(items)}")

Таблицы raw.orders и dicts.items успешно созданы!
Строк в заказах: 10, Строк в товарах: 6

In [9]:
query = """
with first_order as(
    select 
        user_id,
        item_id,
        dense_rank() over(partition by user_id order by transaction_datetime) as row_order
    from orders
),
most_ex as(
    select 
        user_id,
        name,
        price,
        row_number() over(partition by user_id order by price desc) as row_price
    from dict.items d join first_order f 
        on d.item_id = f.item_id
        and f.row_order = 1
)
select
    user_id,
    name,
    price
from most_ex
where row_price = 1
"""
result = duckdb.query(query).to_df()
result

   user_id           name    price
0      102  Redmi Note 13  25000.0
1      101      iPhone 15  90000.0
2      103  Redmi Note 13  25000.0

In [8]:
query = """
select distinct on (o.user_id)
    o.user_id,
    i.name,
    i.price
from orders o join dict.items i on o.item_id = i.item_id
order by 
    o.user_id,
    o.transaction_datetime asc,
    i.price desc,
    i.item_id asc
"""
result = duckdb.query(query).to_df()
result

   user_id           name    price
0      101      iPhone 15  90000.0
1      102  Redmi Note 13  25000.0
2      103  Redmi Note 13  25000.0

In [13]:
df = orders.merge(items)
df.sort_values(['user_id', 'transaction_datetime', 'price'], ascending=[True, True, False]).drop_duplicates(subset=['user_id'], keep='first')[['user_id', 'name', 'price']]

   user_id           name    price
3      101      iPhone 15  90000.0
8      102  Redmi Note 13  25000.0
4      103  Redmi Note 13  25000.0

In [26]:
first_orders = orders[orders.groupby('user_id')['transaction_datetime'].rank(method='dense') == 1]
first_orders.merge(items).sort_values(['user_id', 'price'], ascending=[True, False]).drop_duplicates(subset=['user_id'], keep='first')[['user_id', 'name', 'price']]

   user_id           name    price
2      101      iPhone 15  90000.0
4      102  Redmi Note 13  25000.0
3      103  Redmi Note 13  25000.0

In [35]:
first_time = orders.groupby('user_id')['transaction_datetime'].transform('min')
light_orders = orders[orders['transaction_datetime'] == first_time][['user_id', 'item_id']]
merged_items = light_orders.merge(items[['item_id', 'name', 'price']], on='item_id')
final_idx = merged_items.groupby('user_id')['price'].idxmax()
merged_items.loc[final_idx, ['user_id', 'name', 'price']]

   user_id           name    price
2      101      iPhone 15  90000.0
4      102  Redmi Note 13  25000.0
3      103  Redmi Note 13  25000.0

25. Нам нужно оценить эффективность работы курьеров. Конкретно: нужно найти заказы, у которых сборка или доставка заняли аномально много времени, и понять, в каких районах города это происходит чаще всего.

Таблицы в базе (5 штук)
orders (Заказы)

order_id (int)

city_id (int)

created_at (timestamp) — время создания заказа клиентом

order_status_log (Лог изменения статусов заказа)

order_id (int)

status (varchar) — статусы: 'created', 'packing' (сборка), 'delivery' (передан курьеру), 'delivered' (доставлен)

updated_at (timestamp) — время перехода в этот статус

couriers (Курьеры)

courier_id (int)

city_id (int)

transport_type (varchar) — тип транспорта: 'car', 'bicycle', 'foot'

courier_orders (Назначение курьеров на заказы)

order_id (int)

courier_id (int)

assigned_at (timestamp) — время назначения курьера на заказ

cities (Справочник городов)

city_id (int)

city_name (varchar) — название города (например, 'Москва', 'Новосибирск')

Твое задание
Для каждого города и типа транспорта курьера посчитай:

Количество доставленных заказов.

Среднее время доставки заказа курьером (время между переходом заказа в статус 'delivery' и переходом в статус 'delivered').

Хитрые условия фильтрации:
Нас интересуют только те заказы, сборка которых (packing) началась не позднее, чем через 15 минут после создания заказа (created_at в таблице orders). Если склад тормозил и собирал дольше — этот заказ для оценки курьеров мы не берем.

В расчет должны попасть только те курьеры, которые за всё время успешно доставили более 10 заказов (это фильтр курьеров, а не городов!).

Если у заказа по какой-то причине нет лога перехода в статус 'delivery' или 'delivered', этот конкретный заказ должен быть проигнорирован в расчете среднего времени, но не должен ломать расчет других заказов.

Ожидаемый результат
Колонки: city_name, transport_type, delivered_orders_count, avg_delivery_duration_minutes.

In [2]:
import pandas as pd

# 1. Справочник городов (3 строки)
cities_data = {
    'city_id': [1, 2, 3],
    'city_name': ['Москва', 'Новосибирск', 'Санкт-Петербург']
}
cities = pd.DataFrame(cities_data)

# 2. Таблица курьеров (5 строк)
couriers_data = {
    'courier_id': [10, 20, 30, 40, 50],
    'city_id': [1, 1, 2, 2, 3],
    'transport_type': ['car', 'bicycle', 'bicycle', 'foot', 'car']
}
couriers = pd.DataFrame(couriers_data)

# 3. Таблица заказов (5 строк)
orders_data = {
    'order_id': [1001, 1002, 1003, 1004, 1005],
    'city_id': [1, 1, 2, 2, 3],
    'created_at': [
        '2026-06-01 10:00:00', # Заказ 1001 (Москва, курьер 10)
        '2026-06-01 11:00:00', # Заказ 1002 (Москва, курьер 20)
        '2026-06-01 12:00:00', # Заказ 1003 (Новосибирск, курьер 30)
        '2026-06-01 13:00:00', # Заказ 1004 (Новосибирск, курьер 40)
        '2026-06-01 14:00:00'  # Заказ 1005 (Питер, курьер 50)
    ]
}
orders = pd.DataFrame(orders_data)
orders['created_at'] = pd.to_datetime(orders['created_at'])

# 4. Назначение курьеров на заказы (5 строк)
courier_orders_data = {
    'order_id': [1001, 1002, 1003, 1004, 1005],
    'courier_id': [10, 20, 30, 40, 50],
    'assigned_at': [
        '2026-06-01 10:05:00', '2026-06-01 11:05:00',
        '2026-06-01 12:05:00', '2026-06-01 13:05:00',
        '2026-06-01 14:05:00'
    ]
}
courier_orders = pd.DataFrame(courier_orders_data)
courier_orders['assigned_at'] = pd.to_datetime(courier_orders['assigned_at'])

# 5. Лог изменения статусов (15 строк во всех списках)
order_status_log_data = {
    'order_id': [
        1001, 1001, 1001, # Заказ 1001: Сборка началась вовремя (через 5 мин). Доставлен за 30 мин.
        1002, 1002, 1002, # Заказ 1002: Сборка началась ПОЗДНО (через 20 мин). Должен отсеяться.
        1003, 1003, 1003, # Заказ 1003: Сборка вовремя. Доставлен за 45 мин.
        1004, 1004,       # Заказ 1004: Нет статуса 'delivered' (в процессе). Должен отсеяться.
        1005, 1005, 1005  # Заказ 1005: Сборка вовремя. Доставлен за 20 мин.
    ],
    'status': [
        'packing', 'delivery', 'delivered',
        'packing', 'delivery', 'delivered',
        'packing', 'delivery', 'delivered',
        'packing', 'delivery',
        'packing', 'delivery', 'delivered'
    ],
    'updated_at': [
        # Заказ 1001 (Создан 10:00)
        '2026-06-01 10:05:00', '2026-06-01 10:15:00', '2026-06-01 10:45:00',
        # Заказ 1002 (Создан 11:00) -> packing в 11:20 (> 15 минут, мимо)
        '2026-06-01 11:20:00', '2026-06-01 11:35:00', '2026-06-01 12:10:00',
        # Заказ 1003 (Создан 12:00)
        '2026-06-01 12:10:00', '2026-06-01 12:20:00', '2026-06-01 13:05:00',
        # Заказ 1004 (Создан 13:00) -> нет доставлен
        '2026-06-01 13:02:00', '2026-06-01 13:15:00',
        # Заказ 1005 (Создан 14:00)
        '2026-06-01 14:01:00', '2026-06-01 14:10:00', '2026-06-01 14:30:00'
    ]
}
order_status_log = pd.DataFrame(order_status_log_data)
order_status_log['updated_at'] = pd.to_datetime(order_status_log['updated_at'])

print("Все логистические датафреймы успешно созданы!")
print(f"Городов: {len(cities)}, Курьеров: {len(couriers)}, Логов статусов: {len(order_status_log)}")

Все логистические датафреймы успешно созданы!
Городов: 3, Курьеров: 5, Логов статусов: 14

In [ ]:
query = """

"""
result = duckdb.query(query).to_df()
result

26. Когортный анализ Retention:  
У вас есть две таблицы:

users: информация о пользователях (уникальный идентификатор и дата регистрации)
user_id
signup_ts

user_activity: события, совершаемые пользователями (идентификатор, дата и тип события)
signup_ts
activity_ts
event_name

Задача: необходимо написать SQL-запрос для расчета когортного удержания (retention rate) помесячно для каждой когорты.

Определения:

Когорта (cohort) — это пользователи, зарегистрировавшиеся в одном и том же календарном месяце (определяется из даты signup_ts в таблице users).
Месяц удержания 0 (month 0) — это месяц регистрации пользователя.
Месяц удержания n (month n) — это календарный месяц, который наступает через n месяцев после месяца регистрации.
Пользователь считается удержанным в месяце n, если у него есть хотя бы одно событие в таблице user_activity в течение этого календарного месяца.
События, произошедшие до регистрации пользователя, игнорируются.

Результат: запрос должен выдать таблицу, содержащую следующие столбцы:

cohort_month — месяц когорты (первый день месяца, например 2025-01-01).
months_since_signup — номер месяца удержания (целое число от 0 до N).
cohort_size — общее количество пользователей в когорте.
retained_users — количество уникальных пользователей из когорты, которые были активны в этот месяц удержания.
retention_rate — процент удержания (retained_users / cohort_size).

In [2]:
import pandas as pd

# 1. Таблица пользователей (6 строк)
# Формируем две когорты: январь 2026 и февраль 2026
users_data = {
    'user_id': [1, 2, 3, 4, 5, 6],
    'signup_ts': [
        '2026-01-15 10:00:00', '2026-01-20 14:30:00', '2026-01-25 09:00:00', # Когорта 2026-01-01 (3 юзера)
        '2026-02-10 11:15:00', '2026-02-15 16:00:00',                         # Когорта 2026-02-01 (2 юзера)
        '2026-03-01 12:00:00'                                                  # Когорта 2026-03-01 (1 юзер)
    ]
}
users = pd.DataFrame(users_data)
users['signup_ts'] = pd.to_datetime(users['signup_ts'])

# 2. Таблица активности пользователей (12 строк во всех списках)
# Наполняем так, чтобы проверить расчет month 0, month 1 и т.д.
user_activity_data = {
    'user_id': [
        1, 1, 1, # Юзер 1 (Январь): активен в январе (month 0), феврале (month 1) и марте (month 2)
        2, 2,    # Юзер 2 (Январь): активен в январе (month 0) и марте (month 2, пропустил месяц 1)
        3,       # Юзер 3 (Январь): системная ошибка (событие ДО регистрации, должно быть проигнорировано)
        4, 4,    # Юзер 4 (Февраль): активен в феврале (month 0) и марте (month 1)
        5,       # Юзер 5 (Февраль): активен только в феврале (month 0)
        1, 6, 2  # Дополнительные действия для разнообразия
    ],
    'activity_ts': [
        '2026-01-15 10:05:00', '2026-02-05 14:00:00', '2026-03-10 11:00:00',
        '2026-01-22 18:00:00', '2026-03-15 09:30:00',
        '2025-12-31 23:59:59', # Событие юзера 3 до его регистрации в январе 2026
        '2026-02-11 10:00:00', '2026-03-01 15:20:00',
        '2026-02-15 16:05:00',
        '2026-01-20 09:00:00', '2026-03-05 14:00:00', '2026-01-22 19:00:00'
    ],
    'event_name': [
        'login', 'view_item', 'purchase',
        'login', 'purchase',
        'click', 
        'login', 'click',
        'login',
        'click', 'login', 'view_item'
    ]
}
user_activity = pd.DataFrame(user_activity_data)
user_activity['activity_ts'] = pd.to_datetime(user_activity['activity_ts'])

# Перемешиваем логи активности для симуляции реальной СУБД
user_activity = user_activity.sample(frac=1, random_state=42).reset_index(drop=True)

print("Датафреймы для когортного анализа успешно созданы!")
print(f"Пользователей в базе: {len(users)}, Записей активности: {len(user_activity)}")

Датафреймы для когортного анализа успешно созданы!
Пользователей в базе: 6, Записей активности: 12

In [6]:
# наилучший вариант SQL
import duckdb
query = """
with cohort_base as(
    select 
        user_id,
        date_trunc('month', activity_ts) as month_act
    from user_activity
    group by 
        user_id,
        date_trunc('month', activity_ts)
),
cohort_size as(
    select
        date_trunc('month', signup_ts) as cohort,
        count(*) as cohort_size 
    from users
    group by cohort
),
retained as(
    select 
        date_trunc('month', signup_ts) as cohort,
        date_diff('month', date_trunc('month', signup_ts), month_act) as month_passed
    from cohort_base t join users u 
        on u.user_id = t.user_id
        and t.month_act >= date_trunc('month', u.signup_ts)
),
retained_agg as(
    select
        cohort,
        month_passed,
        count(*) as retained_users
    from retained
    group by 
        cohort,
        month_passed
)
select 
    cohort,
    cohort_size,
    month_passed,
    retained_users,
    round(100 * retained_users / cohort_size,0) as RR
from retained_agg join cohort_size using(cohort)
order by 
    cohort,
    month_passed
"""
result = duckdb.query(query).to_df()
result

      cohort  cohort_size  month_passed  retained_users     RR
0 2026-01-01            3             0               2   67.0
1 2026-01-01            3             1               1   33.0
2 2026-01-01            3             2               2   67.0
3 2026-02-01            2             0               2  100.0
4 2026-02-01            2             1               1   50.0
5 2026-03-01            1             0               1  100.0

In [ ]:
# наилучший вариант python
user_activity['act_month'] = user_activity['activity_ts'].dt.to_period('M')
agg_act = user_activity[['user_id', 'act_month']].drop_duplicates()
users['cohort_month'] = users['signup_ts'].dt.to_period('M')
cohort_size = (
    users.groupby('cohort_month')['user_id']
    .nunique()
    .reset_index(name='cohort_size')
)
df_joined = users.merge(agg_act, on='user_id', how='inner')
df_joined = df_joined[df_joined['act_month'] >= df_joined['cohort_month']]
df_joined['months_since_signup'] = (
    (df_joined['act_month'].dt.year - df_joined['cohort_month'].dt.year) * 12 
    + (df_joined['act_month'].dt.month - df_joined['cohort_month'].dt.month)
)
count_mau = (
    df_joined.groupby(['cohort_month', 'months_since_signup'])['user_id']
    .nunique()
    .reset_index(name='retained_users')
)
result = count_mau.merge(cohort_size, on='cohort_month', how='inner')
result['retention_rate'] = (100 * result['retained_users'] / result['cohort_size']).round()
result.sort_values(['cohort_month', 'months_since_signup']).reset_index(drop=True)

In [ ]:
df_agg_act = user_activity.copy()
df_agg_act['month_act'] = df_agg_act['activity_ts'].dt.to_period('M')
df_agg_act = df_agg_act[['user_id', 'month_act']].drop_duplicates()
df_retained = df_agg_act.merge(users)
df_retained['cohort'] = df_retained['signup_ts'].dt.to_period('M')
df_retained = df_retained[df_retained['month_act'] >= df_retained['cohort']]
df_retained['month_passed'] = (df_retained['month_act'] - df_retained['cohort']).apply(lambda x: x.n)
df_retained_agg = df_retained[['cohort', 'month_passed']].value_counts().reset_index(name='retainefd_users')
df_cohort = users.copy()
df_cohort['cohort'] = df_cohort['signup_ts'].dt.to_period('M')
df_cohort_agg = df_cohort['cohort'].value_counts().reset_index(name='cohort_size')
result = df_retained_agg.merge(df_cohort_agg)
result['RR'] = (100 * result['retained_users'] / result['cohort_size']).round()
result.sort_values(['cohort', 'month_passed']).iloc[:,[0, 3, 1, 2, 4]]

In [ ]:
query = """
with agg_act as(   
    select 
        user_id,
        date_trunc('month', activity_ts) as act_month
    from user_activity
    group by user_id, date_trunc('month', activity_ts)
),
count_mau as(
    select
        date_trunc('month', signup_ts) as cohort_month,
        (extract(year from act_month) - extract(year from signup_ts)) * 12 + extract(month from act_month) - extract(month from signup_ts) as months_since_signup,
        count(distinct u.user_id) as retained_users
    from users u join agg_act a 
        on u.user_id = a.user_id
        and act_month >= date_trunc('month', signup_ts)
    group by 
        date_trunc('month', signup_ts),
        ((extract(year from act_month) - extract(year from signup_ts)) * 12 + extract(month from act_month) - extract(month from signup_ts))
),
cohort_size as(
    select 
        date_trunc('month', signup_ts) as cohort_month,
        count(distinct user_id) as cohort_size
    from users
    group by date_trunc('month', signup_ts)
)
select 
    cohort_month,
    months_since_signup,
    cohort_size,
    retained_users,
    round(100 * retained_users / cohort_size) as retention_rate
from count_mau join cohort_size using(cohort_month)
ORDER BY cohort_month, months_since_signup;
"""
result = duckdb.query(query).to_df()
result

27. Асимметричные курсы валют и мультивалютный финтех  
Контекст
Финтех-платформа проводит транзакции в разных валютах. Нам нужно собрать ежемесячную отчетность по выручке в рублях (RUB) только по реальным (не тестовым) пользователям.

Сложность
Курсы валют обновляются на бирже только по будням (с понедельника по пятницу). Однако пользователи совершают покупки каждый день, включая выходные. Если транзакция совершена в субботу или воскресенье, для неё нужно взять курс валюты за ближайшую предшествующую пятницу.

Таблицы в базе:   
users (Пользователи)
- user_id (int) — идентификатор
- registration_date (date)
- is_test (int) — флаг: 1 (тестовый аккаунт), 0 (реальный пользователь)

transactions (Покупки)
- tx_id (int) — идентификатор платежа
- user_id (int) — кто купил
- amount (numeric) — сумма в локальной валюте
- currency (varchar) — код валюты (например, 'USD', 'EUR')
- tx_date (date) — дата покупки (любой день недели)

currency_rates (Курсы валют)
- currency (varchar) — код валюты
- rate_to_rub (numeric) — курс обмена на рубли
- rate_date (date) — дата фиксации курса (только будние дни)

Задание: напиши запрос, который выведет месяц (в формате 'YYYY-MM' или первого числа месяца) и суммарную выручку в рублях (RUB) за этот месяц, не учитывая тестовых пользователей.

In [ ]:
import pandas as pd

# 1. Таблица пользователей (5 строк)
users_data = {
    'user_id': [1, 2, 3, 4, 5],
    'registration_date': ['2026-05-01', '2026-05-02', '2026-05-10', '2026-05-15', '2026-05-20'],
    'is_test': [0, 0, 1, 0, 0] # Юзер 3 — тестовый (его транзакции должны полностью отсеяться)
}
users = pd.DataFrame(users_data)
users['registration_date'] = pd.to_datetime(users['registration_date'])

# 2. Справочник курсов валют (8 строк — только будни, с Пн по Пт)
# 22 мая 2026 — Пятница, 25 мая 2026 — Понедельник
rates_data = {
    'currency': ['USD', 'EUR', 'USD', 'EUR', 'USD', 'EUR', 'USD', 'EUR'],
    'rate_to_rub': [75.0, 85.0, 76.0, 86.0, 75.5, 85.2, 77.0, 87.0],
    'rate_date': [
        '2026-05-20', '2026-05-20', # Среда
        '2026-05-21', '2026-05-21', # Четверг
        '2026-05-22', '2026-05-22', # Пятница (этот курс зафиксируется на все выходные)
        '2026-05-25', '2026-05-25'  # Понедельник
    ]
}
currency_rates = pd.DataFrame(rates_data)
currency_rates['rate_date'] = pd.to_datetime(currency_rates['rate_date'])

# 3. Таблица транзакций (10 строк — любые дни недели)
transactions_data = {
    'tx_id': range(1001, 1011),
    'user_id': [
        1, 1,  # Юзер 1: Будние дни (прямое совпадение курса)
        2, 2,  # Юзер 2: Покупки в Сб и Вс (должны забрать курс за пятницу 22-го мая)
        3,     # Юзер 3: Покупка тестового пользователя (должна отсеяться)
        4, 4,  # Юзер 4: Покупки в понедельник и среду
        5, 5, 5 # Юзер 5: Разные валюты в выходные
    ],
    'amount': [100.0, 50.0, 200.0, 150.0, 500.0, 10.0, 120.0, 300.0, 80.0, 100.0],
    'currency': ['USD', 'EUR', 'USD', 'EUR', 'USD', 'USD', 'EUR', 'USD', 'EUR', 'USD'],
    'tx_date': [
        '2026-05-20', '2026-05-21', # Будни (Ср, Чт)
        '2026-05-23', '2026-05-24', # Выходные (Сб, Вс -> ищут курс от 2026-05-22)
        '2026-05-22',               # Пятница (тестовый юзер, мимо)
        '2026-05-25', '2026-05-20', # Будни (Пн, Ср)
        '2026-05-23', '2026-05-24', # Выходные (Сб, Вс -> ищут курс от 2026-05-22)
        '2026-05-25'                # Будни (Пн)
    ]
}
transactions = pd.DataFrame(transactions_data)
transactions['tx_date'] = pd.to_datetime(transactions['tx_date'])

print("Все мультивалютные датафреймы успешно созданы!")
print(f"Пользователи: {len(users)}, Курсы: {len(currency_rates)}, Транзакции: {len(transactions)}")

In [ ]:
# более быстрый вариант за счет distinct on
query = """
with t_rate as(
    select distinct on (tx_id)
        date_trunc('month', tx_date) as month,
        amount,
        coalesce(rate_to_rub, 1) as rate
    from transactions t left join currency_rates c
        on t.currency = c.currency
        and tx_date >= rate_date
    where user_id in(select user_id from users where is_test = 0)
    order by 
        tx_id,
        tx_date desc
)
select
    month,
    sum(amount * rate) as sum_transactions
from t_rate
group by month
"""
result = duckdb.query(query).to_df()
result

In [ ]:
query = """
with t_rate as(
    select
        date_trunc('month', tx_date) as month,
        amount,
        coalesce(rate_to_rub, 1) as rate,
        row_number() over(partition by tx_id order by tx_date desc) as row_date
    from transactions t left join currency_rates c
        on t.currency = c.currency
        and tx_date >= rate_date
    where user_id in(select user_id from users where is_test = 0)
)
select
    month,
    sum(amount * rate) as sum_transactions
from t_rate
where row_date = 1
group by month
"""
result = duckdb.query(query).to_df()
result

In [ ]:
real_users = set(users[users['is_test'] == 0]['user_id'])
t_filtered = transactions[transactions['user_id'].isin(real_users)].copy()
t_filtered = t_filtered.sort_values('tx_date')
rates_sorted = currency_rates.sort_values('rate_date')
t_join = pd.merge_asof(
    t_filtered,
    rates_sorted,
    left_on='tx_date',
    right_on='rate_date',
    by='currency',
    direction='backward'
)
t_join['rate_to_rub'] = t_join['rate_to_rub'].fillna(1)
t_join['amount_rub'] = t_join['amount'] * t_join['rate_to_rub']
t_join['month'] = t_join['tx_date'].dt.to_period('M')
t_join.groupby('month', as_index=False).agg(sum_transactions=('amount_rub', 'sum'))

## 28. Оценка каналов привлечения
У нас есть таблица orders:
- date
- Order_id
- client_id
- revenue

и таблица campaign:
- Order_id
- date
- campaign

Задание: Напишите единый SQL-запрос, который для каждой маркетинговой кампании выведет:
- Количество уникальных новых клиентов, которых привлекла эта кампания (первая покупка в истории клиента).
- Количество заказов, которые эта кампания сгенерировала от новых клиентов (new).
- Количество заказов от вернувшихся клиентов (returned, более 60 дней без покупок).
- Количество заказов от постоянных клиентов (regular, 60 дней и менее с прошлой покупки).
- Дополнительный бизнес-метрика: Суммарную выручку (revenue), полученную именно от «вернувшихся» заказов, чтобы оценить финансовый эффект реанимации

In [6]:
import duckdb
import pandas as pd

# 1. Создаем таблицу с заказами (t1)
t1_data = {
    "date": pd.to_datetime(
        [
            "2026-01-10",  # id 101: 1-й заказ (NEW)
            "2026-01-15",  # id 102: 1-й заказ (NEW)
            "2026-02-05",  # id 101: 2-й заказ (через 26 дней -> REGULAR)
            "2026-03-01",  # id 103: 1-й заказ (NEW)
            "2026-03-10",  # id 103: 2-й заказ (через 9 дней -> REGULAR)
            "2026-04-01",  # id 102: 2-й заказ (через 76 дней -> RETURNED)
            "2026-05-01",  # id 104: 1-й заказ (NEW)
            "2026-05-15",  # id 101: 3-й заказ (через 99 дней -> RETURNED)
        ]
    ),
    "order_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "client_id": [101, 102, 101, 103, 103, 102, 104, 101],
    "revenue": [1500, 2300, 800, 5000, 1200, 3100, 4000, 2200],
    "city": [
        "Moscow",
        "Kazan",
        "Moscow",
        "SPb",
        "SPb",
        "Kazan",
        "Sochi",
        "Moscow",
    ],
}
orders = pd.DataFrame(t1_data)

# 2. Создаем таблицу с выгрузкой из GA (t2)
t2_data = {
    "order_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "date": pd.to_datetime(
        [
            "2026-01-10",
            "2026-01-15",
            "2026-02-05",
            "2026-03-01",
            "2026-03-10",
            "2026-04-01",
            "2026-05-01",
            "2026-05-15",
        ]
    ),
    "campaign": [
        "yandex_cpc",  # Заказ 1 (101 - NEW)
        "vk_target",  # Заказ 2 (102 - NEW)
        "telegram_ads",  # Заказ 3 (101 - REGULAR)
        "telegram_ads",  # Заказ 4 (103 - NEW)
        "telegram_ads",  # Заказ 5 (103 - REGULAR)
        "yandex_cpc",  # Заказ 6 (102 - RETURNED)
        "vk_target",  # Заказ 7 (104 - NEW)
        "yandex_cpc",  # Заказ 8 (101 - RETURNED)
    ],
}
campaign = pd.DataFrame(t2_data)

In [7]:
query = """
with order_lifecycle as(
    select
        c.campaign,
        o.client_id,
        row_number() over(partition by o.client_id order by o.date, o.order_id) as order_seq,
        o.revenue,
        o.date,
        lag(o.date) over(partition by client_id order by o.date, order_id) as lag_date
    from campaign c left join orders o using(order_id)
)
select 
    campaign,
    count(distinct case when order_seq = 1 then client_id end) as count_unique_clients,
    count(case when lag_date is null then 1 end) as count_new_orders,
    count(case when extract(day from(date - lag_date)) > 60 then 1 end) as count_returned_orders,
    count(case when extract(day from (date - lag_date)) <= 60 then 1 end) as count_regular_orders,
    sum(case when extract(day from(date - lag_date)) > 60 then revenue else 0 end) as revenue_from_returned_orders
from order_lifecycle
group by campaign
order by count_unique_clients desc
"""
result = duckdb.query(query).to_df()
result

,campaign,count_unique_clients,count_new_orders,count_returned_orders,count_regular_orders,revenue_from_returned_orders
0,vk_target,2,2,0,0,0.0
1,yandex_cpc,1,1,2,0,5300.0
2,telegram_ads,1,1,0,2,0.0

In [ ]:
idx = orders.groupby('client_id')['date'].idxmin()
first_orders = orders.loc[idx,['order_id', 'client_id']]
unique_clients = first_orders.merge(campaign)
unique_clients = unique_clients.groupby('campaign', as_index=False).agg(count_unique_clients=('client_id', 'nunique'))
df = campaign.merge(orders)
df = df.sort_values(['date', 'order_id'])
df['lag_date'] = df.groupby('client_id')['date'].shift()
df['diff'] = (df['date'] - df['lag_date']).dt.days
df['new_order'] = df['lag_date'].isna()
df['returned'] = df['diff'] > 60
df['regular'] = df['diff'] <= 60
df['revenue_returned'] = df['revenue'] * df['returned']
df_orders = df.groupby('campaign', as_index=False).agg(
    count_new_orders = ('new_order', 'sum'),
    count_returned_orders = ('returned', 'sum'),
    count_regular_orders = ('regular', 'sum'),
    revenue_from_returned_orders = ('revenue_returned', 'sum')
)
unique_clients.merge(df_orders).sort_values('count_unique_clients', ascending=False)

,campaign,count_unique_clients,count_new_orders,count_returned_orders,count_regular_orders,revenue_from_returned_orders
1,vk_target,2,2,0,0,0
0,telegram_ads,1,1,0,2,0
2,yandex_cpc,1,1,2,0,5300

## 29 Retention Сбербанк
Нужно посчитать когортный Retention. Когорты формируются по месяцам "активации". Т.е. рассчитать, какой процент устройств активны (есть сессии) на n месяц после активации устройства.

**Таблица:** sessions

**Вывести:**
- тип устройства (например, tv)
- месяц когорты активации (например, январь 2025)
- количество устройств в когорте (например, 10000)
- номер месяца активности от активации устройства (например, 3)
- доля вернувшихся пользователей в данный номер месяца (например, 0.30)

In [7]:
import numpy as np
import pandas as pd
import duckdb

# Фиксируем seed для воспроизводимости
rng = np.random.default_rng(42)

# ---------------------------
# 1. Генерация sessions
# ---------------------------
users = [f'u{idx:05d}' for idx in range(1, 3001)]
device_types = ['box', 'tv']

rows = []
sid = 1

for u in users:
    first_dt = pd.Timestamp('2024-11-01') + pd.to_timedelta(int(rng.integers(0, 150)), unit='D')
    
    for _ in range(int(rng.integers(1, 18))):
        ts = (
            first_dt 
            + pd.to_timedelta(int(rng.integers(0, 130)), unit='D') 
            + pd.to_timedelta(int(rng.integers(0, 86400)), unit='s')
        )
        rows.append((u, rng.choice(device_types), f's_{sid}', ts))
        sid += 1

sessions = (
    pd.DataFrame(rows, columns=['device_id', 'device_type', 'session_id', 'session_ts'])
    .sort_values('session_ts')
    .reset_index(drop=True)
)

# ---------------------------
# 2. Генерация events
# ---------------------------
events_rows = []

for user in users[:1800]:
    dt = rng.choice(device_types)
    base = pd.Timestamp('2026-02-01') + pd.to_timedelta(int(rng.integers(0, 27)), unit='D')
    
    for _ in range(int(rng.integers(2, 12))):
        t = base + pd.to_timedelta(int(rng.integers(0, 86400)), unit='s')
        
        # device_start
        events_rows.append((user, dt, 'device_start', int(t.timestamp())))
        
        # промежуточные события
        for _ in range(int(rng.integers(3, 10))):
            t += pd.to_timedelta(int(rng.integers(10, 420)), unit='s')
            events_rows.append((
                user, 
                dt, 
                rng.choice(['main_screen_open', 'click_menu', 'click_button', 'start_app']), 
                int(t.timestamp())
            ))
        
        # device_end (с вероятностью 90%)
        if rng.random() < 0.9:
            t += pd.to_timedelta(int(rng.integers(30, 1600)), unit='s')
            events_rows.append((user, dt, 'device_end', int(t.timestamp())))

events = (
    pd.DataFrame(events_rows, columns=['device_id', 'device_type', 'event_type', 'timestamp'])
    .sort_values('timestamp')
    .reset_index(drop=True)
)

# ---------------------------
# Проверка
# ---------------------------
print("sessions shape:", sessions.shape)
print("events shape:  ", events.shape)

display(sessions.head())
display(events.head())

sessions shape: (26673, 4)
events shape:   (93042, 4)

  device_id device_type session_id          session_ts
0    u01239          tv    s_11101 2024-11-01 09:01:52
1    u02732          tv    s_24345 2024-11-01 23:04:49
2    u00024         box      s_248 2024-11-02 02:17:46
3    u01551         box    s_14048 2024-11-02 16:48:18
4    u01176          tv    s_10533 2024-11-02 23:31:56

  device_id device_type    event_type   timestamp
0    u00813          tv  device_start  1769904010
1    u00196         box  device_start  1769904119
2    u00813          tv  click_button  1769904143
3    u00196         box     start_app  1769904198
4    u00064          tv  device_start  1769904357

In [8]:
query = """
with base as(
  select distinct
    device_id,
    device_type,
    date_trunc('month',session_ts) as act_date
  from sessions
),
cohorts as(
  select
    device_id,
    device_type,
    min(act_date) as cohort
  from base
  group by device_id, device_type
),
cohort_size as(
  select
    device_type,
    cohort,
    count(*) as cohort_size
  from cohorts
  group by device_type, cohort
),
month_passed as(
  select
    cohort,
    c.device_id,
    c.device_type,
    date_diff('month', cohort, act_date) as month_passed
  from cohorts c left join base a
    on c.device_id = a.device_id
    and c.device_type = a.device_type
)
select
  c.device_type,
  c.cohort,
  cohort_size,
  month_passed,
  round(100.0 * count(*) / cohort_size,2) as share_retained
from cohort_size c left join month_passed m
  on c.cohort = m.cohort
  and c.device_type = m.device_type
group by c.device_type, c.cohort, cohort_size, month_passed
order by c.device_type, c.cohort, month_passed
"""
result = duckdb.query(query).to_df()
result

   device_type     cohort  cohort_size  month_passed  share_retained
0          box 2024-11-01          218             0          100.00
1          box 2024-11-01          218             1           68.35
2          box 2024-11-01          218             2           67.89
3          box 2024-11-01          218             3           66.51
4          box 2024-11-01          218             4           52.29
..         ...        ...          ...           ...             ...
77          tv 2025-05-01          137             1           35.77
78          tv 2025-05-01          137             2           24.09
79          tv 2025-06-01           43             0          100.00
80          tv 2025-06-01           43             1           27.91
81          tv 2025-07-01           17             0          100.00

[82 rows x 5 columns]

In [43]:
base = (
    sessions.assign(act_date=sessions['session_ts'].dt.to_period('M'))
    [['device_type', 'device_id', 'act_date']]
    .drop_duplicates()
)
base['cohort'] = base.groupby(['device_type', 'device_id'])['act_date'].transform('min')
base['month_passed'] = base['act_date'].astype(int) - base['cohort'].astype(int)
cohort_size = (
    base[['device_type', 'device_id', 'cohort']]
    .drop_duplicates()
    .groupby(['cohort', 'device_type'])
    .size()
    .reset_index(name='cohort_size')
)
result = cohort_size.merge(base, on=['cohort', 'device_type'], how='left')
result = result.groupby(['device_type', 'cohort', 'cohort_size', 'month_passed']).size().reset_index(name='retained')
result['share_'] = (100.0 * result['retained'] / result['cohort_size']).round(2)
result.sort_values(['device_type', 'cohort', 'month_passed'])

   device_type   cohort  cohort_size  month_passed  retained  share_
0          box  2024-11          218             0       218  100.00
1          box  2024-11          218             1       149   68.35
2          box  2024-11          218             2       148   67.89
3          box  2024-11          218             3       145   66.51
4          box  2024-11          218             4       114   52.29
..         ...      ...          ...           ...       ...     ...
77          tv  2025-05          137             1        49   35.77
78          tv  2025-05          137             2        33   24.09
79          tv  2025-06           43             0        43  100.00
80          tv  2025-06           43             1        12   27.91
81          tv  2025-07           17             0        17  100.00

[82 rows x 6 columns]

## 30 — Воронка активности

Построить простую воронку `продажа -> активация -> активность в 2026`. Активация - это первая сессия устройства.

**Вывести:**
- тип устройства (например, tv)
- количество проданных устройств (например, 100000)
- количество активированных устройств (например, 90000)
- количество активных устройств в 2026 году (например, 10000)
- конверсии

**devices - в ней все уникальные устройства**
- **device_id** - id устройства
- **device_type** - тип устройства
- **model** - модель устройства
- **sale_date** - дата продажи
- **sale_channel** - канал продажи

**sessions - в ней все сессии активности устройств. Сессия - период непрерывного использования устройства**
- **device_id** - id устройства
- **session_id** - id сессии активности
- **session_ts** - дата-время начала сессии

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Настройка генератора случайных чисел
rng = np.random.default_rng(2026)

# Создание данных об устройствах
users = [f'u{idx:06d}' for idx in range(1, 10001)]
device_types = ['box', 'tv', 'ring']
models = {
    'box': ['sb-100', 'sb-999'], 
    'tv': ['tv-56', 'tv-59'], 
    'ring': ['rg-mini', 'rg-plus']
}
channels = ['site', 'ozon', 'wb', 'offline', 'ym']

devices = []
for u in users:
    d = rng.choice(device_types, p=[0.45, 0.45, 0.10])
    sale_date = pd.Timestamp('2023-01-01') + pd.to_timedelta(int(rng.integers(0, 1100)), unit='D')
    devices.append((u, d, rng.choice(models[d]), sale_date.date(), rng.choice(channels)))

devices_df = pd.DataFrame(
    devices, 
    columns=['device_id', 'device_type', 'model', 'sale_date', 'sale_channel']
)

# Создание данных о сессиях
sessions = []
sid = 1
for row in devices_df.itertuples(index=False):
    if rng.random() > 0.83:
        continue
    first = pd.Timestamp(row.sale_date) + pd.to_timedelta(int(rng.integers(0, 180)), unit='D')
    for _ in range(int(rng.integers(1, 30))):
        ts = first + pd.to_timedelta(int(rng.integers(0, 520)), unit='D') + pd.to_timedelta(int(rng.integers(0, 86400)), unit='s')
        sessions.append((row.device_id, f's_{sid}', ts))
        sid += 1

sessions_df = pd.DataFrame(
    sessions, 
    columns=['device_id', 'session_id', 'session_ts']
).sort_values('session_ts')

# Создание данных о событиях
apps = ['okko', 'ivi', 'youtube', 'kinopoisk', 'wink']
events = []

for row in devices_df.sample(7000, random_state=42).itertuples(index=False):
    for _ in range(int(rng.integers(2, 14))):
        t = pd.Timestamp('2026-02-01') + pd.to_timedelta(int(rng.integers(0, 27)), unit='D') + pd.to_timedelta(int(rng.integers(0, 86000)), unit='s')
        events.append((row.device_id, row.device_type, 'device_start', int(t.timestamp()), None))
        
        for _ in range(int(rng.integers(3, 10))):
            t += pd.to_timedelta(int(rng.integers(10, 500)), unit='s')
            if rng.random() < 0.35:
                app = rng.choice(apps)
                events.append((row.device_id, row.device_type, 'start_app', int(t.timestamp()), app))
                t += pd.to_timedelta(int(rng.integers(60, 5000)), unit='s')
                events.append((row.device_id, row.device_type, 'finish_app', int(t.timestamp()), app))
            else:
                events.append((
                    row.device_id, 
                    row.device_type, 
                    rng.choice(['main_screen_open', 'click_menu', 'click_button']), 
                    int(t.timestamp()), 
                    None
                ))
        
        if rng.random() < 0.9:
            t += pd.to_timedelta(int(rng.integers(30, 1200)), unit='s')
            events.append((row.device_id, row.device_type, 'device_end', int(t.timestamp()), None))

events_df = pd.DataFrame(
    events, 
    columns=['device_id', 'device_type', 'event_type', 'timestamp', 'app']
).sort_values('timestamp')

# Вывод информации о созданных датасетах
print("✅ Временные датасеты созданы!")
print(f"📊 devices_df: {devices_df.shape[0]:,} строк, {devices_df.shape[1]} колонок")
print(f"📊 sessions_df: {sessions_df.shape[0]:,} строк, {sessions_df.shape[1]} колонок")
print(f"📊 events_df: {events_df.shape[0]:,} строк, {events_df.shape[1]} колонок")

print("\n📋 Пример данных devices_df:")
print(devices_df.head())

print("\n📋 Пример данных sessions_df:")
print(sessions_df.head())

print("\n📋 Пример данных events_df:")
print(events_df.head())

✅ Временные датасеты созданы!
📊 devices_df: 10,000 строк, 5 колонок
📊 sessions_df: 123,518 строк, 3 колонок
📊 events_df: 523,432 строк, 5 колонок

📋 Пример данных devices_df:
  device_id device_type    model   sale_date sale_channel
0   u000001         box   sb-999  2023-01-30         ozon
1   u000002         box   sb-999  2024-05-28         ozon
2   u000003          tv    tv-59  2025-02-13      offline
3   u000004          tv    tv-56  2023-07-15         ozon
4   u000005        ring  rg-plus  2025-03-11         ozon

📋 Пример данных sessions_df:
       device_id session_id          session_ts
98984    u007989    s_98985 2023-01-20 00:35:39
78544    u006341    s_78545 2023-01-20 07:37:20
11957    u000940    s_11958 2023-01-23 09:03:31
7113     u000555     s_7114 2023-01-26 16:30:40
111952   u009043   s_111953 2023-01-27 01:18:44

📋 Пример данных events_df:
       device_id device_type    event_type   timestamp   app
175023   u004627         box  device_start  1769904004  None
264488   u007758          tv  device_start  1769904015  None
466102   u003513        ring  device_start  1769904054  None
154431   u009925         box  device_start  1769904073  None
175024   u004627         box  click_button  1769904106  None

In [20]:
query = """
with last_sessions as(
    select
        device_id,
        max(session_ts) as last_session
    from sessions_df
    group by device_id
),
funnel as(
    select
        device_type,
        count(device_id) as count_devices,
        count(last_session) as count_activations,
        sum(case when extract(year from last_session) = 2026 then 1 end) as count_act_2026
    from devices_df left join last_sessions using(device_id)
    group by device_type
)
select
    device_type,
    count_devices,
    round(100.0 * count_activations / count_devices,2) as cr_activations,
    count_activations,
    round(100.0 * count_act_2026 / count_activations,2) as cr_act_2026,
    count_act_2026
from funnel
"""
result = duckdb.query(query).to_df()
result

,device_type,count_devices,cr_activations,count_activations,cr_act_2026,count_act_2026
0,tv,4520,82.90,3747,32.29,1210.0
1,ring,979,83.25,815,32.88,268.0
2,box,4501,83.18,3744,32.83,1229.0

In [36]:
last_session_df = sessions_df.groupby('device_id', as_index=False).agg(last_session=('session_ts', 'max'))
df = devices_df.merge(last_session_df, how='left')
df['is_activated'] = df['last_session'].notna().astype(int)
df['is_using_2026'] = (df['last_session'].dt.year == 2026).astype(int)
result = df.groupby('device_type', as_index=False).agg(
    count_devices=('device_id', 'count'),
    count_activations=('is_activated', 'sum'),
    count_act_2026=('is_using_2026', 'sum')
)
result['cr_activations'] = (100.0 * result['count_activations'] / result['count_devices']).round(2)
result['cr_act_2026'] = (100.0 * result['count_act_2026'] / result['count_activations']).round(2)
result[['device_type', 'count_devices', 'cr_activations', 'count_activations', 'cr_act_2026', 'count_act_2026']]

,device_type,count_devices,cr_activations,count_activations,cr_act_2026,count_act_2026
0,box,4501,83.18,3744,32.83,1229
1,ring,979,83.25,815,32.88,268
2,tv,4520,82.90,3747,32.29,1210